---
output:
  pdf_document: default
  html_document: default
---
<!-- ***********INTRODUCTION SECTION*************************************** -->

# Introduction

Skates are the largest and most widely distributed group of batoid fish with approximately 245 species ascribed to two families (@Ebert2007, @McEachran1990). Skates are benthic fish that are found in all coastal waters but are most common in cold temperatures and polar waters [@Ebert2007].

There are eleven species of skates in three genera (Amblyraja, Bathyraja, and Raja) present in the Northeast Pacific Ocean off California, Oregon and Washington (Ebert 2003). Of that number, just three species (Longnose Skate, *Beringraja rhina*; Big Skate, *Beringraja binoculata*; and Sandpaper Skate, *Bathyraja interrupta*) make up over 95 percent of West Coast Groundfish Bottom Trawl Survey (WCGBTS) catches in terms of biomass and numbers, with the Longnose Skate leading in both categories (with 62 percent of biomass and 56 percent of numbers).

Big Skate (*Beringraja binoculata*) is the largest of the skate species in North America with a documented maximum length of 244 cm total length and a maximum weight of 91 kg [@Eschmeyer1983].  The species name “binoculata” (two-eyed) refers to the prominent ocellus at the base of each pectoral fin.  Big Skates are usually seen buried in sediment with only their eyes showing.

## Biology

Big Skate is oviparious, and is one of two skate species that have multiple embryos per egg case [@Ebert2008]. From 1–8 embryos can be contained in a single, large egg capsule, but most have 3–4 [@DeLacy1935; @Hitz1964; @Ford1971]. Eggs are deposited year-round on sand or mud substrates at depths of ~50–150 m [@Hitz1964; @Ebert2007]. Embryos hatch from eggs after 6–20 months, with shorter developmental periods associated with warmer temperatures [@Hoff2009]. In captivity, Big Skate females may produce > 350 eggs/year (average of 2 embryos/egg case; @Chiquillo2014) from long-term sperm storage . Size at birth is 18–23 cm TL [@Ebert2003]. Maximum size is 244 cm TL [@Eschmeyer1983], with females growing to larger sizes.

<!-- long-term sperm storage [@Jang2009] -->

Size at maturity has been variably estimated for Big Skate populations off California, British Columbia, and Alaska. Off central California, Zeiner and Wolf [-@ZeinerWolf1993] reported sizes at first maturity of ~129 cm TL (females) and ~100 cm TL (males).  A similar size at maturity was estimated for females from the Gulf of Alaska (first = 126 cm TL, 50% = 149 cm TL), but male estimates were considerably greater (first = 124 cm TL, 50% = 119 cm TL; @Ebert2008).  Much smaller sizes at first (female = 60 cm TL, male = 50 cm TL) and 50% (female = 90 cm TL, male = 72 cm TL) maturity were generated for the Longnose Skate populations off British Columbia [@McFandKing2006]; however, maturity evaluation criteria were flawed (subadults were considered to be mature), and these results are therefore not considered valid.

Age and growth parameters have been established from California, British Columbia, and the Gulf of Alaska. Maximum ages off central California (females = 12, males = 11; @ZeinerWolf1993) and in the Gulf of Alaska (females = 14, males = 15; Gburski et al. 2007) were similar, but estimates off British Columbia were much greater (females = 26, males = 25; McFarlane and King 2006). It is important to note that age estimates are based on an unvalidated method and geographic differences in size or age may reflect differences in sampling or ageing criteria. In the Gulf of Alaska, Big Skates reach 50% maturity at 10 years and 7 years for females and males, respectively (@Gburski2007, @Ebert2008). Generation length estimates range from 11.5 [@ZeinerWolf1993] to 17 years [@McFandKing2006]. 

\vspace{.5cm}
\FloatBarrier


```{r, results='asis'}
#
Life_History = read.csv('./txt_files/BigSkate_LifeHistory.csv', as.is=T)

colnames(Life_History) = Life_History[1,]
Life_History = Life_History[-1,]

LH1 = c("1st Maturity (TL cm)",
       "50% Maturity (TL cm)",
       "Max Age (year)",
       "1st Maturity (year)",
       "50% Maturity (year)"
)

Life_History = cbind(LH1, Life_History)
colnames(Life_History)[1] = ""


a_header <- construct_header(
  # the data.frame or matrix that should be plotted
  Life_History,
  # the labels of the groups that we want to insert
  grp_names = c("", "California", "British Columbia","Gulf of Alaska"),
  # the number of columns each group spans
  span = c(1,2,2,2),
  # the alignment of each group, can be a single character (lcr) or a vector
  align = "c"
)


Life_History.table = xtable(Life_History,
                          caption = c("Regional comparison of life history parameter estimates."),
                          label='tab:Life_Hist')


 align(Life_History.table) = c('l', 'l',
                               '>{\\centering}p{0.6in}',
                               '>{\\centering}p{0.6in}',
                               '>{\\centering}p{0.6in}',
                               '>{\\centering}p{0.6in}',
                               '>{\\centering}p{0.6in}',
                               '>{\\centering}p{0.6in}')
 
print(Life_History.table, add.to.row = a_header, 
      caption.placement = "top", 
      include.rownames = F, hline.after = F)

```


\FloatBarrier
## Distribution and Life History

The Big Skate is most common in soft-sediment habitats in coastal waters of the continental shelf (@Bizzarro2014, @Farrugia2016). Use of mixed substrate (e.g., mud with boulders) increases with ontogeny but hard substrates are largely avoided (@Bizzarro2015).  In the GOA, the Big Skate is the most commonly encountered skate species in continental shelf waters at 100–200 m depth, and is most abundant in the central and western areas of the GOA (@Stevenson2008; @Bizzarro2014). Off the U.S. Pacific Coast, the Big Skate is most densely distributed on the inner continental shelf (< 100 m; @Bizzarro2014). Eggs are mainly deposited between 70–90 m on sand or mud substrates (@Hitz1964; NMFS-NWFSC-FRAM, unpub. data). Juveniles typically occur in shallower waters than adults (@Bizzarro2015). Core habitat regions of Big Skate off the U.S. Pacific Coast and in the Gulf of Alaska are spatially segregated from those of other species (@Bizzarro2014).

Big Skates are highly mobile and capable of long range (> 2000 km) movements (@KingandMcF2010; @Farrugia2016). For example, in British Columbia, a study revealed that ~75% of tagged individuals were recaptured within 21 km of the tagging locations, but 15 of the tagged individuals (0.1%) moved over 1,000 km (max = 2340 km; @KingandMcF2010). In the Gulf of Alaska, a year of satellite tag data showed that six of twelve tagged individuals moved over 100 km, with one skate moving > 2,000 km (Farrugia et al.  2016). Although primarily benthic, Big Skates utilize the entire water column including surface waters (@Farrugia2016). They have broad thermal tolerances 2–19º C that enable their occurrence from boreal to subtropical latitudes (@Love2011; @Farrugia2016).

The Big Skate is broadly distributed, occurring from the southeastern Bering Sea [@Mecklenburg2002] to southern Baja California (22.90º N, 110.03º W; [@Castro1993]) and the Gulf of California [@Castro1996]. It has been reported at depths of 2–501 m (min: @Miller1980; max: @Farrugia2016) but is most common on the inner continental shelf (< 100 m; [@Love2011]; [@Bizzarro2015]). Big Skates are highly mobile and capable of long range (> 2000 km) movements ([@KingandMcF2009]; [@Farrugia2016]). 

In 2012, the Big Skate was moved from genus *Raja* to the new genus *Beringraja* together with the Mottled Skate (*B. pulchra*) [@Ishihara2012].  These are the only two skates with multiple embryos per egg case, and they are very similar mophologically and genetically [@Bizzarro2019].  More recently, Longnose Skate has also moved to *Beringraja* [@Last2016].

## Ecosystem Considerations

Big Skates are opportunistic, generalist mesopredators with highly variable spatio-temporal trophic roles (@Ebert2007; @Bizzarro2015). Off central California, diet of Big Skates is composed mainly of fishes, shrimps, and crabs (in descending order), with larger skates incorporating more fishes (@Bizzarro2007); however, in the Gulf of Alaska, Big Skate diet consists mainly of crabs (esp. Tanner Crabs) throughout ontogeny, with relatively small portions of fishes and shrimps (@Bizzarro2015). Correspondingly, trophic level and general diet composition estimates differ significantly between California and Gulf of Alaska Big Skate populations (@Bizzarro2015). 

Big Skates and their egg cases are preyed upon by a variety of vertebrates and invertebrates. Snails and other molluscs bore holes in egg cases to feed on developing embryos and especially their protein rich yolk-sacs (Bizzarro, pers. obs; @Hoff2009). Sevengill Sharks, Brown Rockfish, and Stellar Sea Lions are known predators of juvenile and adult Big Skates (@Ebert2003, @Love2011). Northern Sea Lions consume free-living Big Skates and their egg cases (@Ebert2003, @Love2011).

In this assessment, neither environmental nor ecosystem considerations were explicitly included in the analysis. This is primarily due to a lack of relevant data or results of analyses that could contribute ecosystem-related quantitative information for the assessment.

## Fishery Information

Big Skate are caught in commercial and recreational fisheries on the West Coast using line and trawl gears. There is a limited market for pectoral fins (skate wings).

The history of Big Skate is not well documented.  They were used as a food source by the native Coastal and Salish Tribes [@Batdorf1990] long before Europeans settled in the Pacific Northwest and then as fertilizer by the settlers [@Bowers1909].  No directed fishery for Big Skate has been documented; rather, they were taken along with other skates and rays as "scrap fish" and used for fertilizer, fish meal and oil [@GregLippert].

Skates have been regarded as a predator on desirable market species such as Dungeness crab, and were thought of as nuisance fish with no appeal as a food item save for small local markets. They had been discarded or harvested at a minimal level until their livers became valued along with those of other cartilaginous fishes for the extraction of vitamin A in the 1940s.  Chapman [-@Chapman1944] recorded that “At present they are being fished heavily, in common with the other elasmobranchs of the coast, for the vitamins in their livers. The carcasses are either thrown away at sea or made into fish meal.  Little use is made of the excellent meat of the wings”.

Little information is available about the historic Washington fishery for Big Skate.  In records before 2000, they are lumped together with other skates or in market categories [@GregLippert]; this necessitates considerable attention to reconstructing the fishery by observing the composition of skate catches in the modern fishery and applying those to the recently reconstructed historical records.

Very little information is known about the Big Skate historical fishery in Oregon. The information we do have is mainly from historical landing data and species composition samples starting in the mid-nineties. The bulk of the catch is from the bottom trawl and longline fisheries, with smaller amounts as by-catch in mid-water trawl and the shrimp trawl fishery. Big Skate was lumped into the nominal “Skate” category until 2015 when it was separated into its own market category. Species composition data have been vitally important in reconstructing the pre-2015 historical catch [@TedCalavan].

## Stock Status and Management History

The history of Big Skate management is documented in [@PFMC2018], reproduced here.

Big Skate were managed in the "Other Fish" complex until 2015 when they were designated an Ecosystem Component (EC) species.  Catches of Big Skate are estimated to have averaged 95 mt from 2007–2011, along with large landings of "Unspecified Skate".  Analysis of Oregon port-sampling data indicates that about 98 percent of the recent Unspecified Skate landings in Oregon were comprised of Big Skate. Such large landings indicates targeting of Big Skate has occurred and an EC designation was not warranted. Based on this evidence, Big Skate was redesignated as an actively-managed species in the fishery. Big Skate has been managed with stock-specific harvest specifications since 2017 [@PFMC2018].

The recent OFL of 541 mt was calculated by applying approximate MSY harvest rates to estimates of stock biomass from the Northwest Fisheries Science Center (NWFSC) West Coast Groundfish Bottom Trawl Survey. This survey-based biomass estimate is likely underestimated since Big Skate are distributed all the way to the shoreline and no West Coast trawl surveys have been conducted in water shallower than 55 meters. This introduces an extra source of uncertainty to management and suggests that increased precaution is needed to reduce the risk of overfishing the stock [@PFMC2018]. 

There has been consideration for managing Big Skate in a complex with Longnose Skate, the other actively-managed West Coast skate species, but the two species have disparate distributions and fishery interactions (Longnose Skate is much more deeply distributed than Big Skate) and that option was not endorsed. The Pacific Fishery Management Council has chosen to set the Annual Catch Limit (ACL) equal to the Allowable Biological Catch (ABC) with a buffer for management uncertainty (P*) of 0.45 [@PFMC2018].

<!-- ## Management Performance -->

<!-- Table \ref{tab:mnmgt_perform} -->


## Fisheries Off Alaska, Canada and Mexico

### Alaska

In Alaska, skates were primarily taken as bycatch in both longline and trawl fisheries until 2003, when a directed skate fishery developed in the Gulf of Alaska, where Longnose and Big Skate comprise the majority of the skate biomass. 

The Gulf of Alaska (GOA) skate complex is managed as three units. Big skates and Longnose Skates each have separate harvest specifications, with acceptable biological catches (ABCs) specified for each GOA regulatory area (western, central, and eastern). A single gulfwide overfishing level (OFL) is specified for each stock. All remaining skate species are managed as an “Other Skates” group with gulfwide harvest specifications. All GOA skates are managed as Tier 5 stocks, where OFL and ABC are based on survey biomass estimates and natural mortality rate [@AFSC2018].

In the Bering Sea and Aleutian Islands, skates are assessed as a group rather than as separate species.

### Canada

In Canada historic information regarding skate catches goes back to the 1950’s. Prior to 1990’s skates were taken mostly as bycatch and landings were reported as part of a skate complex (not by species). As with the U.S. West Coast, the trawl fishery is responsible for the largest amount of bycatch.  Skate catches off British Columbia accelerated in the early 1990’s, partly due to emerging Asian markets. Since 1996, Longnose Skate has been targeted by the B.C. trawl fishery and as a result, catches have been more accurately reported. 

Assessments of Longnose Skate and Big Skate were conducted by Canada's Division of Fisheries and Oceans in 2015 [@King2015].  For Big Skate, a Bayesian surplus production model failed to provide plausible results, and two data-limited approaches were investigated: Depletion-Corrected Average Catch Analysis (DCAC), and a Catch-MSY (maximum sustainable yield) Approach.  

DCAC produced a range of potential yield estimates that were above the long-term average catch, with an upper bound that was three orders of magnitude larger than the long-term average catch. The Catch-MSY approach was found to be quite sensitive to assumptions and was not recommended as the sole basis of advice to managers.

The recommendation for management for both skate species was that they should be managed with harvest yields based on mean historic catch, with consideration given to survey trends and to the ranges of maximum sustainable yield estimates identified by the Catch-MSY Approach. However, the analysis found no significant trends in abundance indices for Big Skate, and mean historical catches were below the maximum MSY estimate from the catch-MSY results.

### Mexico

No information is available on any fishery for Big Skate in Mexican waters, where they rarely occur, however they may be taken in the artisanal fishery.

