---
output:
  pdf_document: default
  html_document: default
---

<!-- ************ASSESSMENT SECTION**************************************** -->
# Fishery Data

## Data
Data used in the `r spp` assessment are summarized in Figure \ref{fig:data_plot}. 
Descriptions of the data sources are in the following sections.



<!-- ************FISHERY-DEPENDENT DATA************************************ -->
## Fishery Landings and Discards

Catch information for Big Skate is very limited, in part because the requirement to sort landings of Big Skate in the shore-based Individual Fishing Quota fishery from landings in the  "Unidentified Skate" category was not implemented until June 2015.  The historical catch of Big Skate therefore relies on the historical reconstruction of the landings of all skates as well as an analysis of discards of Longnose Skate. The estimated landings for each state and the tribal fishery are provided in Table \ref{tab:Reconstructed_Landings_byState} and shown in Figure \ref{fig:catch_by_state}. Landings for the years 1935 onward were assumed to be the sum of the catch reconstructions described below for each of the three coastal states as well as tribal fisheries.

### Washington Commercial Skate Landings Reconstruction

<!-- text in this section is a shortened version of what's in the Longnose document -->
New estimates of landings in Washington were developed in collaboration between NWFSC and Washington Department of Fish and Wildlife (WDFW). Landings from 1940--2003 were estimated as a fraction of the total skate landings based on ratios of species compositions by depth as described in more detail in [@Gertseva2019]. The approach relied on trawl survey estimates of the ratios among all skates by depth bin combined with logbook estimates of fishing depths in each year.

The WCGBT Survey data was used to estimate proportions of Longnose and Big Skates by depth (aggregated into 100m bins) and year for the period of the survey (between 2003 and 2018). Big Skate were primarily found in the 0--100m and 100--200m bins. Trawl logbook data include information on the amount of retained catch of skate (all species combined) within each haul as well depth of catch. The proportion of Big Skate for each depth bin was assigned to the skate catch for each haul within those depth bins and summed to get a total for each year. When survey skate information was available (2003-2018), survey skate proportions were applied by depth and year to account for inter-annual variability in those proportions. For the period prior to 2003, average proportions from 2003-2007 within each depth bin were applied. 

These estimated annual proportions of Big Skate relative to all skates from the logbook analysis was then applied to total Washington skate landings by year (provided by WDFW) to account for landings that weren't included in the available logbook data. For the period prior to 1987 (when no logbook data were available), the average proportion of Big Skate within the combined skate category, calculated from 1987-1992 logbook data, was applied to total skate landings in Washington. Estimated Big Skate landings provided by WDFW were used for the period from 2004 forward. This later period had adequate species composition sampling to divide the unspecified skate category by species with reasonable accuracy.

### Oregon Commercial Skate Landings Reconstruction

<!-- IGT: text below from a Word document Ali Whitman provided
The Calavan et al. 2019 reference is expected to be completed in August to be referenced in the final assessment report.-->

Oregon Department of Fish and Wildlife (ODFW) provided newly reconstructed commercial landings for all observed skate species for the 2019 assessment cycle (1978 -- 2018).
<!-- More detail on the methodology of the reconstruction is provided in Calavan et al. 2019. -->
In addition, the methods were reviewed at a pre-assessment workshop (with report available at https://www.pcouncil.org/groundfish/stock-assessments/by-year/gf-2019/).  Historically, skates were landed as a single skate complex in Oregon.  In 2009, Longnose Skate was separated into its own single-species landing category, and Big Skate was separated in 2014.  The reconstruction methodology differed by these three time blocks in which species composition collections diverged (1978 -- 2008; 2009 -- 2014; 2015 -- 2018).  

Species compositions of skate complexes from commercial port sampling are available throughout this time period but are generally limited, which precluded the use of all stratification variables for reconstructing landings.  Quarter and port were excluded, retaining gear type, PMFC area, and market category for stratifying reconstructed landings within the three time blocks.  Bottom trawl gear types include multiple bottom trawl gears, and account for greater than 98% of skate landings.
<!--  (Calavan et al. 2019) -->
Minor gear types include primarily bottom longline gear, but also include mid-water trawl, hook and line, shrimp trawl, pot gear and scallop dredge.  

For bottom trawl gears, trawl logbook areas and adjusted skate catches were matched with stratum-specific species compositions. In Time Block 1 (1978 -- 2008), all bottom trawl gear types were aggregated due to a lack of specificity in the gear recorded on the fish tickets. However, in Time Blocks 2 and 3, individual bottom trawl gear types were retained.  Some borrowing of species compositions was required (31% of strata) and when necessary, borrowed from the closest area or from the most similar gear type
<!--  (Calavan et al. 2019) -->.
Longline gear landings were reconstructed in a similar fashion as to bottom trawl and required some borrowing among strata as well (25%). <!-- (25% ; Calavan et al. 2019).-->  

Due to insufficient species compositions, mid-water trawl landings were reconstructed using a novel depth-based approach.  Available compositions indicate that the proportion by weight of Big Skate within a composition drops to zero at approximately 100 fathoms, and an inverse relationship is observed for Longnose Skate, where the proportion by weight is consistently one beyond 100 -- 150 fathoms
<!--  (Calavan et al. 2019) -->.
Complex-level landings were assigned a depth from logbook entries and these species specific depth associations were used to parse out landings by species.  The approach differed somewhat by time block.
<!--  (Calavan et al. 2019) -->
Landings from shrimp trawls were handled using a similar methodology. Finally, very minor landings from hook and line, pot gear and scallop dredges were assigned a single aggregated species composition, as they lack any gear-specific composition samples.  Landings from within a time block were apportioned by year using the proportion of the annual ticket landings.   

Results indicate that the species-specific landings from this reconstruction are very similar to those from Oregon's commercial catch reconstruction (Karnowski et al. 2014) during the overlapping years but cover a greater time period with methodology more applicable to skates in particular.  ODFW intends to incorporate reconstructed skate landings into PacFIN in the future [@Whitman2019].  

### California Catch Reconstruction

A reconstruction of historical skate landings from California waters was developed for the 1916–2017 time period using a combination of commercial catch data (spatially explicit block summary catches and port sample data from 2009-2017) and fishery-independent survey data [@Bizzarro2019].  Virtually all landings in California were of “unspecified skate” until species-composition sampling of skate market categories began in 2009. 

From 2009 through 2017, catch estimates were based on these market category species-composition samples, and the average of those species-compositions was hindcast to 2002, based on the assumption that those data were representative of the era of large area closures in the post-2000 period. 

For the period from 1936-1980, spatially explicit landings data (the California Department of Fisheries and Wildlife (CDFW) block summary data) were merged with survey data to provide species-specific estimates.

For years 1981-2001, a “blended” product of these two approaches was taken, in which a linear weighting scheme blended the two sets of catch estimates through that period. Landings estimates were also scaled upwards by an expansion factor for skates landed as “dressed” based on fish ticket data.  Prior to 1981 these data had not been reported and skate landings were scaled by the “average” percentage landed as dressed in the 1981-1985 time period, but by the late 1980s nearly all skates were landed round.
 
As no spatial information on catch is available from 1916-1930, and the block
summary data were very sparse in the first few years of the CDFW fish ticket program
(1931–1934), spatial information from the late 1930's was used to hindcast to the
1916–1935 time period. However, since Washington and Oregon did not have catch estimates for this year period, the California estimates of catch prior to 1939 were not used in the model as they were subsumed into an estimate of the total catch across all states increasing linearly from 1916 to 1950.

### Tribal Catch in Washington
Tribal catch of Big Skate was provided by WDFW as all landings took place in Washington State. The landings were estimated from limited state sampling of species compositions in the combined skate category. Anecdotal evidence suggests that most of the catch in the tribal fishery is retained, and discard is minimal.

### Fishery Discards

Fishery discards of `r spp` are highly uncertain. The method used to estimate discards for Longnose Skate was based on a strong correlation (R^2^ = 95.7%) between total fishing mortality of that species, and total fishing mortality of Dover Sole for the years 2009--2017 during which Longnose were landed separately from other skates. In contrast, the sorting requirement for `r spp` occurred too recently to provide an adequate range of years for this type of correlation. Furthermore, there is greater uncertainty in the total fishing mortality for the shallow-water species with which `r spp` most often co-occurs, such as Sand Sole and Starry Flounder, than there is for Dover Sole, which has been the subject of recurring stock assessments.

The minimal discard rate information that is available for `r spp`,  together with anecdotal information from those involved in the fishery for both skate species indicate that discarding for `r spp` and Longnose Skate in the years prior to 1995 was driven by the same market forces, and the discard rates were similar. Therefore, the discard rate for Longnose Skate was used as a proxy for the discards of Big Skate in order to estimate Big Skate discards as described in more detail below.

The reconstructed landings of Big Skate for the period 1950--1994 had a mean of 63.1 t with no significant trend (a linear model fit to the data increased from 62.8 t in 1950 to 63.5 in 1995). The estimated tribal catch prior to 1995 averaged less than 1 t and was not included in this analysis of Big Skate discards for the years prior to 1995.

The mean discard rate for Longnose Skate in this period was 92.46%, also with no significant linear trend (the linear fit decreased from 92.8% in 1950 to 92.1% in 1995). An estimate of the mean annual discard amount can therefore be calculated as from the mean discard rate and the mean landings as $\bar{L} / (1 - \bar{d})$ where $\bar{L}$ is the mean landings across that time period and $\bar{d}$ is the mean discards (Figure \ref{fig:discard_calculations}).

Two alternative methods were explored to estimate the mean annual discard amount: applying the annual Longnose Skate discard rates to the annual Big Skate landings (as reconstructed for each of the three states), and applying 3-year moving averages of these two quantities. The use of the annual values resulted in an implausibly high degree of annual variability among the estimates, with the most extreme being a spike of 2146.4 in 1979 compared to 1032.7 t the year before and 654.0 the year after. The use of the 3-year moving average damped this variability and these estimates were retained for a sensitivity analysis (Figure \ref{fig:discard_calculations}).

A discard mortality rate of 50 percent was assumed for all discards, following the assumption used for the Longnose Skate assessment conducted for the U.S. West Coast in 2007 [@Gertseva2007] The same rate has been used for skates in the trawl fishery in British Columbia, based on an approximate average of these reported rates. In 2015, PFMC's Groundfish Management Team  (GMT) conducted a comprehensive literature review of skate discard mortality, and concluded that the current assumption regarding Big Skate discard mortality is consistent with existing reported rates for other similar species.

Estimation of discard rates (discard amount relative to total catch) during the period of the West Coast Groundfish Observer Program (WCGOP), which began in 2002, was hindered by the landings of Big Skate primarily occurring in the "unspecified skate" category prior to 2015. Therefore, a discard rate was computed for this period using the combination of Big Skate and unspecified skate, under the assumption that the vast majority of the unspecified skates were Big Skate. A coefficient of variation was calculated for this rate by bootstrapping vessels within ports, because the observer program randomly chooses vessels within ports to be observed. For the years after the catch share program was implemented in 2011, the trawl fishery was subject to 100% observer coverage and discarding is assumed to be known with minimal error (CV = 0.01). 

The model inputs for dead catch by fleet are shown in Figure \ref{fig:catch_input_plot} and the resulting estimates of total dead catch by year, including model estimates of dead discards, are shown in Figure \ref{fig:dead_catches}.

The mean body weight of discarded Big Skates, calculated from the weight and count of baskets of discarded Big Skate, was available for the years 2002--2017.


<!-- ************FISHERY-INDEPENDENT DATA*********************************** -->

# Fishery-Independent Data Sources

## Indices of abundance

Description of two indices used in the model and one that was not included are below. Index values, diagnostics, and maps are provided in Table \ref{tab:index_inputs} and Figures \ref{fig:survey_hauls_map} through \ref{fig:IPHC_map}.

### Alaska Fisheries Science Center (AFSC) Triennial Shelf Survey

Research surveys have been used since the 1970s to provide fishery-independent information about the abundance, distribution, and biological characteristics of `r spp`.  A coast-wide survey was conducted in 1977 [@Gunderson1980] by the Alaska Fisheries Science Center, and repeated every three years through 2001.  The final year of this survey, 2004, was conducted by the NWFSC according to the AFSC protocol. We refer to this as the **Triennial Survey**.

The survey design used equally-spaced transects from which searches for tows in a specific depth range were initiated. The depth range and latitudinal range was not consistent across years, but all years in the period 1980-2004 included the area from 40$^\circ$ 10'N north to the Canadian border and a depth range that included 55-366 meters, which spans the range where the vast majority of `r spp` are encountered in all trawl surveys. Therefore the index was based on this depth range.  The survey as conducted in 1977 had incomplete coverage and is not believe to be comparable to the later years, and is not used in the index.

### Northwest Fisheries Science Center West Coast Groundfish Bottom Trawl Survey

In 2003, the NWFSC expanded the ongoing slope survey to include the continental shelf. This survey, referred to in this document as the "WCGBT Survey" or "WCGBTS", is conducted annually. It uses a random-grid design covering the coastal waters from a depth of 55 m to 1,280 m from late-May to early-October [@Bradburn2011 ; @Keller2017]. Four chartered industry vessels are used in most years. The location of Big Skate catches relative to all survey stations in WCGBT Survey are shown in Figure \ref{fig:survey_hauls_map}. Relative frequency of presence or absence of Big Skate by depth bin is shown in Figure \ref{fig:WCGBTS_presence_absence_by_depth_bin}.

### Index Standardization

The index standardization methods for the two bottom trawl surveys matched that used for Longnose Skate, and additional detail is provided in [@Gertseva2019]. The data from both surveys was analyzed using a spatio-temporal delta-model [@Thorson2015], implemented as the VAST R package [@Thorson2017a], and publicly available online (https://github.com/James-Thorson/VAST).  Spatial and spatio-temporal variation is specifically included in both the encounter probability and positive catch rates, using a logit-link for the encounter probability, and a log-link for the positive catch rates.  Vessel-year effects were included for each unique combination of vessel and year in the database for the WCGBT Survey, but not for the Triennial survey. Further details regarding model structure are available in the user manual (https://github.com/James-Thorson-NOAA/VAST/blob/master/manual/VAST_model_structure.pdf). Gamma and lognormal error structures were considered for the positive catch rates, and the gamma model was chosen based on the patterns in the quantile-quantile (Q-Q) diagnostic plots (Figure \ref{fig:VAST_QQ_plots}).

The VAST geostatistical estimates were compared to a simpler design-based index estimate to ground-truth the geostatistical methods. The design-based estimates were based on the mean catch per swept area within each of four strata, scaled to the area of the strata and combined. The strata were divided at 42 degrees North latitude and at 183 m depth, where the depth boundary is associated with a change in the sampling density of the survey. The two deeper strata were extended to 549 m, the next depth at which sampling density changes in the survey, and beyond the 459 m at which the deepest observation of Big Skate occurred.

The VAST estimates with Gamma error are very similar to the designed-based estimates, while the VAST models with Lognormal error are higher, with greater inter-annual variability (Figures \ref{fig:Triennial_index_compare} and \ref{fig:WCGBTS_index_compare}). The unweighted mean biomass across all years in the WCGBT Survey was 12,143 mt for the design-based estimate and 12,184 mt for the VAST estimate with Gamma error. This difference of less than 1% suggests that interpretation of catchability of the index is not significantly influenced by the use of VAST for standardization, at least for the Gamma error that was chosen.

Spatial patterns in the standardized survey density estimates show Big Skate widely distributed along the coast, with higher densities in the central and more northerly areas and closer to shore (Figures \ref{fig:VAST_Yearly_Dens_Triennial} and \ref{fig:VAST_Yearly_Dens_WCGBTS}). Examination of spatial patterns of the residuals for the encounter probability and catch rate for each of the indices (Figures \ref{fig:VAST_encounter_pearson_TRI} through \ref{fig:VAST_catchrate_pearson}) showed no obvious pattern of misfit to spatial patterns in the observed data.

### International Pacific Halibut Commission Longline Survey

The IPHC has conducted an annual longline survey for Pacific Halibut off the coast of Oregon and Washington since 1997 (no surveys were performed in 1998 or 2000). This survey was considered for inclusion in the assessment model but the encounters of Big Skate are relatively infrequent compared to Longnose Skate and including the survey in early model explorations was found to make little difference in the model results. A description of the survey methods and analysis are included below for consideration in future Big Skate assessments.

Beginning in 1999, this has been a fixed station design, with 84 locations (station locations differed in 1997, and are therefore not comparable with subsequent surveys). 400 to 800 hooks have been deployed at each station in 100-hook groups (typically called “skates” although that term will be avoided here to avoid confusion). The gear used to conduct the survey was designed to efficiently sample Pacific Halibut and used 16/0 (#3) circle hooks baited with Chum Salmon.

In some years from 2011 onward, additional stations were added to the survey to sample Yelloweye Rockfish. These stations were excluded from the analysis, as were additional stations added in 2013, 2014, and 2017, off the coast of California (south of 42 degrees latitude). Some variability in exact sampling location is practically unavoidable, and leeway is given in the IPHC methods to center the set on the target coordinates, while allowing wind and currents to dictate the actual direction in which the gear is deployed. This can result in different habitats being accessed at each fixed deployment location across years. One station that was very close to the U.S. Canada border had the mid-point of the set in Canada in 2 out of the 19 years of the survey. For consistency among years, all samples from this station were included in the analysis, including those in Canada.

In most years, bycatch of non-halibut species has been recorded during this survey on the first 20 hooks of each 100-hook group, although in 2003 only 10\% of the hooks were observed for bycatch, and starting in 2012, some stations had 100\% of the hooks observed for bycatch. Combining these observation pattern with the number of hooks deployed each year resulted in most stations having 80, 100, 120, 140, or 160 hooks observed, with a mean of 144 hooks and a maximum of 800 hooks observed. The depth range of the 84 stations considered was 42—530 m, thus extending beyond the range of Big Skate, but 74\% of the stations were shallower than 200 m. Big Skate have been observed at 51 of the 84 standard stations that were retained for this analysis, but no station had Big Skates observed in more than 12 out of the 19 years of survey data, and only 10\% of the station/year combinations had at least one observed Big Skate (Figure \ref{fig:IPHC_map}). Of those station/year combinations with at least one Big Skate observed, the Big Skates were observed on an average of 1.3\% of the hooks observed. The highest proportion was 10 Big Skates out of 81 hooks observed at one station.

The IPHC longline survey catch data were standardized using a Generalized Linear Model (GLM) with binomial error structure. Catch-per-hook was modeled, rather than catch per station due to the variability in the number of hooks deployed and observed each year. The binomial error structure was considered logical, given the binary nature of capturing (or not) a Longnose Skate on each longline hook. The modeling approach is identical to that which has been applied in the past for Yelloweye Rockfish [@Stewart2009], and Spiny Dogfish [@Gertseva2011]. MCMC sampling of the GLM parameters was used to estimate the variability around each index estimate. The median index estimates themselves were approximately equal to the observed mean catch rate in each year (Figure \ref{fig:IPHC_index}). In recent years, the IPHC standardization of the index of halibut abundance has included an adjustment to account for missing baits on hooks returned empty, in an effort to account for reduced catchability of the gear that may result from the lost bait. This adjustment was not included in the analysis for Big Skate although it could be considered in future years.
