

<!--************BIOLOGICAL DATA*********************************************-->

# Biological Parameters and Data

## Measurement Details and Conversion Factors

Size measurements of skates are not always total-length measurements, requiring conversion factors.  Some size measurements in the data are recorded as either disc width or inter-spiracle width. A conversion factor from disc width to total-length was estimated as $L = 1.3399 * W$, based on 95 samples from the WCGBT Survey, where both measurements were collected (R-squared = 0.9983). Little sex difference is observed, so the data were converted using a single relationship for both sexes (Figure \ref{fig:weight-length}). This estimate is similar to the conversion estimated by Ebert [-@Ebert2008] for Big Skate in Alaska. The inter-spiracle width to total length conversion was based on estimates from Downs & Cheng [-@Downs2013], and does differ by sex:

\begin{centering}

$L = 12.111 + 9.761*ISW$ (females),

$L = 3.824 + 10.927*ISW$ (males).

\end{centering}


<!--
Not sure why this is here:
Love et al.  [-@Love1987] -->

## Fishery dependent length and age composition data

Fishery length composition data from PacFIN were available for the years 1995--2018 (with the exception of 2000) as shown in Table \ref{tab:PacFIN_Samples}.

The length compositions from the fishery and each of the two surveys aggregated across all years is shown in Figure \ref{fig:comp_lendat_aggregated_across_time}.

Ages were available only from 2004, 2008-2012, and 2018. These were all represented in the model as conditioned on length in order to provide more detailed information about the relationship between age and length (Figure \ref{fig:age_dat_fishery}).  Treating the data this way also reduces any influence of size-based selectivity on the age composition, and ensures independence from the length samples. Furthermore, samples recorded in data from Washington in 2009 were sampled using a length-stratified system, and therefore should only be treated as conditioned on length.

Length compositions of Big Skate discarded in commercial fisheries and measured by the West Coast Groundfish Observer program were available for the years 2010--2017.

The input sample sizes for the length compositions were calculated via the Stewart Method [@Stewart2019]:

\begin{centering}

Input N = $N_{\text{trips}} + 0.138 * N_{\text{fish}}$ if $N_{\text{fish}}/N_{\text{trips}}$ is $<$ 44,

Input N = $7.06 * N_{\text{trips}}$ if $N_{\text{fish}}/N_{\text{trips}}$ is $\geq$ 44.

\end{centering}

However, no trip had more than 44 Big Skate sampled, so only the first formula was used.


## Survey length and age composition data

Lengths of Big Skate were only collected from the Triennial survey in 1998, 2001, and 2004, but in 1998 only 3 `r spp` were sampled, so those lengths were excluded from this analysis. Length compositions were available for all years of the WCGBT Survey. Sample sizes for both surveys are provided in Table \ref{tab:Survey_Samples}. The WCGBT Survey measured disc width for the years 2006 and 2007, and total length in all other years. Those samples for which  only disc width was measured were converted to total length using the formula above.

Ages were available from the WCGBT Survey in the years 2009, 2010, 2016, 2017, and 2018 which again were represented as conditioned on length (Figure \ref{fig:age_dat_survey}). No ages were available from the Triennial Survey.

\vspace{.5cm}

**Ageing Precision and Bias**

Ages of Big Skate were all estimated based on growth band counts of sectioned vertebrae. Ageing precision and bias were estimated using double-reads of 518 Big Skate vertebrae using the approach of Punt et al. [-@Punt2008]. The results showed strong agreement among readers (Figure \ref{fig:ageing_comparison}), with a standard deviation of the ageing error increasing from about 0.4 at age 0 to 1.6 years at age 15 (Figure \ref{fig:ageing_imprecision}).

\vspace{.5cm}

**Weight-Length**

The mean weight as a function of length was estimated from 1159 samples from the WCGBT Survey using a linear regression on a log-log scale. Sex was not found to be a significant predictor, so a single relationship was estimated: $Weight = 0.00000749  * Length ^ {2.9925}$ (Figure \ref{fig:weight-length}).

\vspace{.5cm}

**Sex Ratio, Maturity, and Fecundity**

The female maturity relationship was based on visual maturity estimates from port samplers (n = 278, of which 241 were from Oregon and 37 from Washington, with 24 mature specimens) as well as 55 samples from the WCGBT Survey (of which 4 were mature). The resulting relationship was $L_{50\%} = 148.245$ with a slope parameter of $Beta = -0.13155$ in the relationship $M = (1 + Beta(L - L_{50\%}))^{-1}$ (Figure \ref{fig:maturity}). This result is consistent with the estimated maturity of Big Skate in Alaska (Table \ref{tab:Life_Hist}).

Fecundity was assumed to be proportional to body weight for mature females, as no relationship has been estimated between body weight and the annual number of egg cases produced (and/or embryos per egg case).

\vspace{.5cm}

## Environmental or Ecosystem Data Included in the Assessment

In this assessment, neither environmental nor ecosystem considerations were explicitly included in the analysis.  This is primarily due to a lack of relevant data or results of analyses that could contribute ecosystem-related quantitative information for the assessment.




