
# Assessment

<!-- ***********HISTORY AND CURRENT ASSESSMENT***************************** -->
## Previous Assessments

<!-- ### History of Modeling Approaches Used for this Stock -->

This analysis represents the first stock assessment that has been conducted for Big Skate. The current management of the stock is based on an OFL estimate calculated from a proxy for $F_{MSY}$ and average survey biomass from the WCGBT Survey during the years 2010--2012 [@Taylor2013]. The $F_{MSY}$ estimate was based on the product of an assumed $F_{MSY}/M$ ratio and an $M$ estimate of 0.162 based on the maximum age of 26 reported by McFarlane and King [@McFandKing2006]. Values were sampled from an assumed distribution around all these quantities to develop a measure of uncertainty around the OFL estimate.

<!-- ************************MODEL DESCRIPTION***************************** -->
## Model Description

### Modeling Software

The STAT team used Stock Synthesis version 3.30.13 (@Methot2013, @Methot2019).
The r4ss package version 1.35.1 [@Taylor2019] was used to post-process the output data from Stock Synthesis.

### Summary of Data for Fleets and Areas

Catch is divided among 4 fleets in the base model:

\begin{itemize}
\item Fishery (current) combines all non-tribal sources of catch for the years 1995 onward,
\item Discard (historical) is the estimated discard amount calculated from the estimated Longnose Skate discard rate as described above. The input catch for this fleet was 50\% of the total estimate, to account for the assumed 50\% discard mortality rate. This data covers the period 1916--1994.
\item Fishery (historical) includes the reconstructed landings estimates from each of the three states for 1916--1994.
\item Tribal includes the estimates of catch of Big Skate by treaty tribes.
\end{itemize}

The use of a separate fleet for historical discards allowed greater flexibility in choosing how to model discards outside the model, but also prevented  uncertainty in those estimates to be propagated through to the estimated uncertainty in the model results. All four fleets were assumed to have the same selectivity.

A retention function was estimated for the current fishery, and discards were estimated within the model based on the fit to discard rates and mean body weight of the discarded fish (along with all other data in the integrated analysis). The choice to model retention explicitly only for the current fishery implies that the historical landings and historical discards represented the same subset of the population. During the historical period, the landed catch is likely to have contained fewer small fish than the discards, but the estimated discard rate is greater than 90\%, so it necessarily includes fish of all sizes. During the historical period, skates were used for animal food and reduction to fish meal or fertilizer, markets which may have accepted skate of all sizes.

### Other Specifications

This assessment covers the U.S. West Coast stock of Big Skate in off the coasts of Washington, Oregon and California, the area bounded by the U.S.-Canada border to the north, and the U.S.-Mexico border to the south. The population is treated as a single coastwide stock with no net movement in or out of the area. Females and males are modeled separately as there is evidence for differences in growth based on both the age and length data, as well as patterns in the sex ratios associated with the length composition data. Natural mortality is estimated within the model using a natural mortality prior developed by Hamel [-@Hamel2015]. A Beverton-Holt stock-recruit function is assumed.  No deviations from the spawner-recruit curve are estimated. 

The length composition data are stratified into 37 5-cm bins, ranging between 20 and 200 cm. The age data are stratified into ages 0--15+, conditioned on the same length bin structure. The population dynamics are computed over a larger range of lengths-at-age, with the 5-cm length bins extending up to 250 cm and the numbers-at-age computed up to age 20.

### Data Weighting

The Francis data weighting method "TA1.8" [@Francis2011], as implemented in the r4ss package was used for all length and age composition data. This method is based on adjusting the input sample sizes to make the variability in mean length or age around the model expectation match the variability expected based on the adjusted input sample size. Sensitivity analyses to both the McAllister-Ianelli tuning method [@McAllister1997] and a Dirichlet-Multinomial approach [@Thorson2017c] were also explored.

The weight given to the indices of abundance was adjusted automatically through the estimation of an additional standard deviation parameter for each index, which was added to the standard deviation values estimated within the index standardization process.

No data-weighting algorithm was applied to the discard rate or mean body weight observations.

### Priors

*Natural Mortality*
A log-normal prior for natural mortality was based on the Hamel [-@Hamel2015] meta-analysis. The Hamel prior for M is lognormal(ln(5.4/max age), .438). For `r spp`, the maximum age is based on the single 15-year-old fish observed out of 1034 ages from the WCGBT Survey. This results in a lognormal(log(0.36) = --1.021651, 0.438) prior.

<!--If it needs to be fixed, it should be set to M = 5.4/max age = 5.4/15 = 0.36 -->

\vspace{.5cm}

*Survey Catchability*
The lack of contrast in the data resulted in unstable model results under a variety of configurations. In order to keep biomass estimates within a plausible range, the assessment uses a revised prior on the WCGBT Survey catchability parameter ($q$) that is based on one that was originally developed for the 2007 Longnose Skate assessment (@Gertseva2007, @Dorn2007), and is being used for the concurrent Longnose Skate assessment [@Gertseva2019]. The description that follows first addresses the method used to develop the original prior, followed by a description of the additional work used to tailor it for Big Skate.

The original prior is based on consideration of the availability of Longnose Skate to the survey gear and the probability that a skate in the path of the gear would be caught and retained by the gear. The methodology for developing the prior involves identifying factors that contribute to Longnose Skate catch in trawl gear, specifying the potential range in the proportion of fish that are available to the gear according to each factor, and the potential range in the vulnerability to the gear.  These are “best guesses” for the individual probabilities associated with each factor.  These values are translated into a lognormal prior where the median of the lognormal is the “best guess” and the range of plausible values covers 99% of the lognormal distribution.

Four factors inform catchability in the survey.  The WCGBT Survey covers the full latitudinal range of Longnose Skate modeled in the assessment, and thus, the latitudinal availability factor was assumed to be one (complete latitudinal coverage).  The survey coverage exceeds the maximum depth distribution of Longnose Skates but doesn't fully cover the shallow end of the skate distribution.  A range of 95 to 100 percent was assumed for the depth availability in the 2007 Longnose Skate prior, but this was revised for Big Skate as noted below.  A range of 75 to 95 percent was assumed for vertical availability on the basis that skates are known to bury in the mud, and therefore some may be unavailable to the bottom trawl gear.  

The largest bounds were placed on the probability of capture, given that a fish is in the net path.  It is known that flatfish can be herded by trawl gear, and it is possible that this could also occur for skates.  However, it is also possible that skate could avoid the trawl nets.  For the capture probability, a range of 75 to 150 percent was assumed.  The best estimates for each of these factors were set at the midpoint of the range for individual factors, except for the probability of capture, which was given a value of one. The overall estimate in the Longnose Skate prior for the survey catchability was the product of the best estimates, 0.83.  The bounds on catchability are the products of the low and high values for factor ranges, respectively, which are 0.53 and 1.43. The overall estimate was equated to the median of a lognormal distribution, and the bounds to 99% of that distribution. This gave a normal prior on $log(q)$, with mean  --0.188 and a standard deviation of 0.187.

Two additional factors were developed for revising the WCGBTS prior for the present (2019) Big Skate assessment. These focused on the assumptions about depth availability, and on accounting for untrawlable habitat.  

Big Skate have a shallower depth distribution than Longnose Skate, and encounters in the WCGBT Survey are most frequent in the shallowest depths (Figure \ref{fig:WCGBTS_presence_absence_by_depth_bin}). The area of the coastal waters within the 55--200 m depth range where Big Skate are most often found was estimated at 4.17 million hectares [@Whitmire2019]. The area shallower than 55 m which is not included in the survey is estimated at is 1.61 million ha, or 38.5% of the area within 55--200 m. 

An analysis of trawl fishery data (involving both discarded and retained fish) provided insight into the changes in Big Skate density by depth. An ODFW Flatfish survey conducted in the 1970s [@Mirick2019] was also considered as a source of information, however we found that there were very few hauls in that study with Big Skate (in 42 of 350 hauls), relative to the fishery data (where Big Skate were present in 14,896 of 160,168 hauls), so that data was ultimately not used in the analysis.

The following steps were used to estimate the fraction of Big Skate biomass unavailable to the WCGBT Survey due to occurring shallower than the 55 m limit of the survey design (Figure \ref{fig:survey_estimates_by_depth_with_shallow}).
\begin{itemize}
  \item Catch data provided by the WCGOP program comprising both retained and discard catch was utilized after filtering for bottom trawl gear and the years 2015-2017 during which Big Skate were landed in a separate market category.
  \item The ratio of hauls containing Big Skate to all hauls was calculated in each of four depth bins:  (0-25], (25-55], (55-75], and (75-100] meters.
  \item The analysis was stratified by the following regions: Washington (46-49 degrees N latitude), Oregon (42-46 degrees N), Northern California (36-42 degrees), and Southern California (32-36 degrees). However, during the range of years chosen, sufficient data were only available for trips that had landings in Northern California and Oregon, so the estimates for Oregon were assumed representative of Washington and the estimates of Northern California were assumed representative of Southern California.
  \item The median biomass of Big Skate in hauls in those same depth bins was calculated.
  \item The median biomass was combined with the fraction of hauls containing Big Skate to get a relative biomass among these depth bins within each region.
  \item The ratios among the 0-25, 25-55, and 55-75 meter bins were applied to the catch rates in the survey for the 55-75 bin within each region to extrapolate the survey catch rates into the shallower water.
  \item The extrpolated catch rates in each depth bin within each region were expanded by the spatial area of that bin to get an absolute estimate of biomass in each case.
\end{itemize}

The resulting estimates showed the largest amount of unsurveyed biomass occurred in Northern California where the commercial catch rate was highest in the 25-55 m depth bin (Figure \ref{fig:survey_estimates_by_depth_with_shallow}). This was consistent with patterns in the survey data which showed this region was the only one where the survey biomass estimate was highest in the shallowest surveyed depth bin. Commercial fishery catch rates in Oregon declined almost linearly from the 55-75 m bin to the two shallower bins. The survey data for Washington and Oregon had similar catch rates in the 55-75 m bin so the assumption of applying the same ratio from the commercial data to the shallower bins seems reasonable. Southern California had the lowest catch rates in the WCGBT Survey so the assumption of using the Northern California fishery catch rates for this area was unlikely to have much influence on the total extrapolation regardless of how representative the commercial catch rates from Northern California are for this area.

The extrapolated biomass shallower than 55 m, combined across all regions, represented 25.8% of the total biomass (extrapolated plus surveyed area). This value was used as the basis for reducing the best guess for the "Depth availability" component of the catchability prior from 0.975 used in the 2007 Longnose Skate assessment to 0.75 with minimum and maximum values changed from 0.95 and 1.0 to 0.6 and 0.9, respectively (Table ?? below).

A further change to the prior was made to add a "Habitat availability" component to account for the possibility raised during the STAR panel that Big Skate density was likely to be lower in untrawlable habitat untrawlable habitat --- the areas where survey operations have not taken place because the bottom is too rugged or too steep. Big Skate are unlikely to occur in these rugose bottom types, so the extrapolation of the survey density is likely to overestimate the biomass of Big Skate for these areas. There is no quantitative estimate of untrawlable habitat for the survey region, so an approximation was made based on the fraction of survey cells that had failed searches for trawlable habitat, which was 625 cells out of 7098 cells visited up through 2017, or 8.8% [@Whitmire2019]. This is likely an underestimate because some cells which have had successful tows include untrawlable area as well. Thus, a best guess value of 1.1 was used to account for the overestimation of Big Skate biomass due to untrawlable habitat, with a range of 1.0-1.2.

The product of the 5 factors resulted in a value of 0.701 for the combined best guess survey catchability, reduced from 0.83 in the Longnose Skate prior. The bounds were also broader at 0.338 for the minimum and 1.539 for the maximum, compared to 0.53 and 1.43 for the Longnose Skate prior.

A lognormal prior based on the three values was calculated following the basic approach used for the 2007 Longnose Skate prior. The minimum and maximum values were first shift slightly to equidistant from the best guess value on a log scale. The log of the min, best guess, and max values were --1.086, --0.355, and 0.431, with an average difference of 0.759. Equidistant min and max values were calculated as min = $exp(-0.355 - 0.759) = 0.328$ and max = $exp(-0.355 + 0.759) = 1.497$. A lognormal distribution with median 0.701 and log-standard deviation 0.326 has 1% and 99% quantiles at the equally proportioned min and max values. This was represented in the Stock Synthesis model as a normal prior on $log(q)$ with mean = $log(0.701) = -0.355$ and standard deviation = 0.326.

During the STAR panel, a revised version of the new prior was explored, where the "minimum" and "maximum" values assigned to the 10% and 90% quantiles, but this was found to be too uninformative (the 95% interval on spawning biomass encompassed 0) and insufficiently representative of the prior belief about catchability, so the final model retained the 1% and 99% quantile assumption used in development of the Longnose Skate catchability prior as described above.

\vspace{.5cm}

<!-- ***********Indices of abundance summary table************************* -->
```{r, results = "asis"}
    Catch_prior = read.csv("./txt_files/Catchability_prior.csv")
      colnames(Catch_prior) = c("Factor",
                                  "Minimum",
                                  "Best Guess",
                                  "Maximum")

   # Index of abundance summary, create table   
     Catch_prior.table = xtable(Catch_prior, 
                                 caption = c("Factors used in the analysis of the catchability prior ($q$)."),
                                 label = "tab:Catch_prior",
                                 align = c("l","l", rep("c", 2),"r"))

    # Print index summary table
      print(Catch_prior.table, 
            include.rownames=FALSE, 
            caption.placement="top",
            sanitize.text.function = function(x){x})
```
<!-- ---------------------------------------------------------------------- -->

### Estimated Parameters

A full list of all estimated and fixed parameters is provided in Tables 
\ref{tab:model_params}. 

The base model has a total of 44 estimated parameters in the following categories:

\begin{itemize}
  \item 1 stock-recruit parameter ($log(R_0)$ controlling equilibrium recruitment)
  \item 1 natural mortality parameter applied to both sexes,
  \item 6 parameters related to female growth and the variability in length at age
  \item 2 parameters relating male growth to female growth,
  \item 3 catchability parameters (1 for the WCGBT Survey and 1 each for the early and late periods of the Triennial Survey)
  \item 2 extra standard deviation parameters (1 for each survey)
  \item 29 selectivity parameters, including 16 related to time-varying retention rate
\end{itemize}

The estimated parameters are described in greater detail below and a full list of 
all estimated and fixed parameters is provided in Table \ref{tab:model_params}.

_Recruitment_
The parameter $log(R_0)$ is the log of the equilibrium recruitment (in thousands). Other aspects of the stock-recruit relationship are described below under Fixed Parameters.

_Natural Mortality._
Male natural mortality was assumed equal to the value estimated for females. Sensitivity analyses were used to test the impact of both the prior on natural mortality and the assumption of equal natural mortality for both sexes.

_Growth._ 
Examination of patterns of age-at-length and length-at-age indicated unusual patterns of growth for Big Skate.  The youngest fish show near-linear growth, and average size for both sexes is similar.  However, older fish show considerable sex-based differences in size. This led to the choice to model growth using the "growth cessation model" recently developed by Maunder et al. [-@maunder2018growth]. The estimated growth curves are shown in Figure \ref{fig:growth}. The growth cessation model provided two key advantages over the more common von Bertalanffy growth model in the case of Big Skate: it allowed essentially linear growth for the early years and it allowed growth for the earlier ages to be similar between females and males while diverging at older ages. The growth cessation model also improve the negative log-likelihood by 45 units relative to the von Bertalanffy growth model.

_Selectivity._  
A double-normal selectivity function was used for all fleets to allow consideration of both asymptotic and dome-shaped patterns. No length composition data was available for the historical fishery, the historical discards, or the tribal fishery, so selectivity was assumed equal for all fisheries in all time periods, and will be referenced simply as "the fishery" in many areas below. For the fishery and the Triennial survey, the difference in likelihood between dome-shaped and asymptotic patterns was very small and in the case of the Triennial survey, the dome-shape occurred at a length beyond almost all observations, indicating that this shape was likely driven by the fit to other data sources, such as the index, rather than the length composition data. The WCGBT Survey was allowed to remain dome-shaped, as as the model estimated the selectivity peak at a smaller length than the other fleets, and the likelihood was improved by the dome-shape. The WCGBT Survey also has the shortest hauls, with 15 minutes or less of bottom contact, so larger skates may be better able to escape the net.

In order to fit a strong skew in the sex ratios toward males for the length bins in which the majority of the samples were found, it was necessary to estimate a sex-specific offset of selectivity. Two offset parameters were estimated for all fleets, one for the difference in length at peak selectivity, and another for the maximum selectivity at that peak.  This allows one sex to have a maximum of 1.0 at the peak and the other to have a maximum less than 1.0. The ascending slope was assumed equal in all cases, as was the descending slope for the WCGBT Survey.

Fishery retention was estimated as a logistic function applied to the selected catch from 1995 onward, to estimate discards within the model. Discards prior to 1995 were estimated outside the model and input as the historical discard fleet as discussed above. Three retention parameters were estimated, the length at 50% retention, a slope parameter, and the asymptotic retention rate. The asymptotic retention rate was estimated as time-varying, with separate parameters covering 1995--2004, individual years from 2005 to 2016, and 2017--onward. The choice of these time blocks was made to allow the model to fit the discard rates during the 2005--2016 period well.  This is the period with the most information about discard rates.  The first three years with data on discard rates and mean body weight of the discarded fish (2002--2004) were used as the basis for the estimate applied to the earlier years, those without discard data.

### Fixed Parameters

The steepness of the Beverton-Holt stock-recruit curve was fixed at 0.4. The same value was used in the 2007 Longnose Skate assessment [@Gertseva2007] and is being considered for the ongoing 2019 Longnose Skate assessment.  This value reflects a K-type reproductive strategy associated with elasmobranchs in general. The influence of the assumption of $h=0.4$ on model output was explored via a likelihood profile analysis. No deviations around the stock-recruit curve were estimated, and the stock was assumed to be at an unfished equilibrium in the first year (1916).

Parameters controlling the weight-length relationship and maturity-at-length were fixed at the externally estimated values.

As noted above, the descending limb of the double-normal selectivity function was fixed at a high value resulting in asymptotic selectivity for both the fishery and the Triennial Survey.

## Model Selection and Evaluation

### Key Assumptions and Structural Choices

The modeled stock was assumed to be a single closed population within the EEZ of the U.S. West Coast, with fishing mortality the only driver of changes in abundance. Neither variability in recruitment nor any other biological or ecological process that would contribute to changes in abundance was included in the final model. Recruitment variability was explored but found to be insufficiently supported by information in the data.

Some modeling choices were made based on similar choices for the concurrent Longnose Skate stock assessment, such as the division of the historical fishery into separate fleets for landed and discarded fish with the same selectivity, and the choice to model the tribal fishery separately in the recent period. In all these cases, alternative approaches would likely have yielded similar results, so the exploration of alternative models focused on the issues that seemed to have the biggest impact on the estimated dynamics.

### Alternate Models Considered

Numerous alternative configurations were explored for growth, selectivity, mortality, and historical discards. A selection of these alternative approaches were retained as sensitivity analyses.

### Convergence

One hundred sets of jittered starting values were generated using the jitter function built into Stock Synthesis, using jitter input = 0.1. The same likelihood as the base model was returned by 51 out of the 100 runs, while the others all had worse outcomes (Table \ref{tab:jitter}). No analysis was conducted for the starting values associated with those jitter runs which failed to return to the same likelihood as the base model, but throughout the model selection process, models which started with a low $log(R_0)$ parameter or other initial values that led to a crashed population had convergence problems. This was straightforward to resolve during the model selection process, but may have been the cause of many of the jittered models failing to reach the best observed likelihood. The 49% failure rate also suggests that the 0.1 jitter input value was high enough to produce a broad range of starting values to test the model, where a very high success rate might suggest too low a jitter value. 


## Response to the Current STAR Panel Requests

Figures illustrating responses to these requests are in Appendix B. <!-- add link -->

\begin{description}[style=sameline]

\item[Request 1: Explore possible changes to the prior distribution on survey q for the West Coast Bottom Trawl Survey.] \hfill \\
  
\textbf{Rationale:} The scale of the population is determined by the assumed prior of the survey q for the West Coast Bottom Trawl Survey, which was based on the 2007 longnose skate assessment.  Longnose skate have a very different depth distribution than big skate which occur in shallower depths than longnose skate or the West Coast Bottom Trawl Survey.

\vspace{.4cm}

\textbf{STAT Response:} An estimate of the fraction of Big Skate biomass unavailable to the survey due to occurrence shallower than 55 m was estimated at 25.8% of the total population as described in detail in the "Priors" section above. ??add link to Priors section??. This was used to revise the "Depth availability" component of the prior calculation. A new component representing "Habitat availability" was also added to account for the potential impact of survey biomass estimate into untrawable habitat which woudl be expected to have lower density of Big Skate. The resulting prior on $log(q)$ had $mean = log(0.701) = -0.355$ and standard deviation 0.326, as compared to the Longnose Skate prior with mean = $log(0.83) = -0.188 and standard deviation = 0.187.

Replacing the Longnose Skate catchability prior with the new Big Skate catchability prior resulted in a lower catchability estimate and a higher biomass (Figure \ref{fig:spawnbio_SRG_request1}).

The revised catchability prior was considered by the STAT to be a better choice for Big Skate and was used in all subsequent analyses with the exception of the responses to Requests 2 below which was conducted concurrently with the revision to the prior.

\item[Request 2: Explore changes to the model to provide better fits to the trawl surveys.] \hfill \\

\textbf{Rationale:} The models explored to date do not fit the survey trends well.

\vspace{.4cm}

\textbf{STAT Response:} The stock assessment team acknowledges that the increasing trends in both the Triennial and WCGBT Surveys is not well fit by the model as discussed at length elsewhere in this report. Models were developed with a start year of 1980 to allow more flexibility in the population size at the start of the survey time series with the hope that this would improve the fit to the survey indices. In one case, the initial conditions were based on an estimated equilibrium fishing mortality with the associated fished equilibrium age structure. In the other case the initial age structure was allowed to be more flexible by estimating recruitment deviations for the years 1965-1980 to allow out-of-equilibrium age structure in 1980.

The model with flexible initial conditions had very similar estimates of unfished equilibrium and current biomass to the pre-STAR base model (Figure \ref{fig:spawnbio_STAR_request2}) while the model with less flexible initial conditions had implausibly low biomass in 1980 and an oscillating pattern of biomass as the population rebuilt from initial conditions associated with the change from a fished equilibrium associated within initial fishing mortality abiout 10 times higher than the estimated mortality for the years 1980-1984. The oscillations in model with less flexible equilibrium conditions fit the both indices of abundance slightly better (by a total of 2.1 units of negative log-likelihood) but the equilibrium catch was implausibly high while the model with more flexible initial conditions had a very similar fit to the indices (Figures \ref{fig:indexfit_WCGBTS_SRG_request2} and \ref{fig:indexfit_Tri_SRG_request2}).


\item[Request 3: Explore a time-varying M model.] \hfill \\

\textbf{Rationale:} To explore this as a mechanism to better fit survey trends.

\vspace{.4cm}

\textbf{STAT Response:}

Time-varying natural mortality ($M$) was imlemented using a wide range of settings related to overall variability and autocorrelation among years in the setup of time-varying natural mortality. In some cases, the resulting time series of $M$ was implausibly variable, while other estimates were more reasonable.\label{fig:tv_M1}. However, the associated time series of biomass and recruitment showed implausible patterns for all but the least flexible setups (Figures \ref{fig:tv_M2} and \ref{fig:tv_M3}). The improvement in the fit to the indices was biggest for the least plausible scenarios and relatively small for the least flexible one (Figures \ref{fig:tv_M4} and \ref{fig:tv_M5}).

This exploration indicated that even a small amount of time-varying natural mortality could explain some of the observed variability in the indices, but the STAT felt that Big Skate did not have sufficient data to reliably estimate time-varying $M$. 



\item[Request 4: Provide a run with the new prior from request \#1 with diagnostics, fits, and likelihood profiles, if possible.] \hfill \\

\textbf{Rationale:} The scale of the population is determined by the assumed prior of the survey q for the West Coast Bottom Trawl Survey, which was based on the 2007 longnose skate assessment.  Longnose skate have a very different depth distribution than big skate which occur in shallower depths than longnose skate or the West Coast Bottom Trawl Survey.  The new prior has more information specific to big skate distribution.
 
\vspace{.4cm}

\textbf{STAT Response:}

A full set of r4ss outputs for this new candidate base model were provided to the STAR panel through the FTP site. Likelihood profiles on catchability and steepness were also provided. The profile with no prior is the same as was provided for the pre-STAR base model (Figure \ref{fig:profile_logQ_noprior}), while the profile including the prior (Figure \ref{fig:profile_logQ}) showed that the change in negative log-likelihood over the range of $q$ = 0.5 to 2.0 was smaller than before, with a change of about 5 units compared to over 10 units for the Longnose Skate catchability prior (not shown).

The steepness profile (Figure \ref{fig:profile_h}) showed that the change in likelihood over the range $h$ = 0.3 to 0.9 was even smaller than in the pre-STAR base model, with a total change of about 0.5 units of negative log-likelihood compared to about 0.7 previously.

\item[Request 5: Provide the diagnostics, fits, and the likelihood profiles associated with the model from run \#4 with Dirichlet weighting.] \hfill\\ 

\textbf{For the likelihood profiles:}

\begin{enumerate}[(1)]\bfseries

\item do not allow the Dirichlet weights to change from the maximum likelihood values
\item allow full implementation of the Dirichlet weighting

\end{enumerate}

\textbf{For both treatments, do not let the estimated SDs for the surveys change from their maximum likelihood estimates.}

\vspace{.4cm}

\textbf{Rationale:} To confirm the model with Dirichlet weights better estimates scale without relying as heavily on the survey q prior.  There is a need to understand what is driving this counter-intuitive result.  This may provide the basis for a new base model.

\vspace{.4cm}
  
\textbf{STAT Response:}


A full set of r4ss outputs for this alternative model were provided to the STAR panel through the FTP site. A likelihood profile was conducted over survey catchability of the survey but there was a problem with convergence requiring further investigation (Figure \ref{fig:profile_logQ_D-M}). As the Dirichlet-Multinomial model was not chosen for the based model, further investigations in the profiles were not attempted.

\item[Request 6: Repeat run \#4 with no survey q prior and a run with the mean of the survey q prior of at half the mean of the prior from run \#4.] \hfill\\

\textbf{Rationale:} To ensure the model is capable of estimating scale.

\vspace{.4cm}

\textbf{STAT Response:}

The $q$ prior from request \#4 had mean 0.701 corresponding to $log(q) = -0.355$. A model with the prior at half this value, $q = 0.3505$, $log(q) = -1.048$ had a maximum likelihood estimate of $q = 0.343$, $log(q) = -1.070$, indicating that the estimated values is closely following the prior. This is expected given the likelihood profile indicated that the best total likelihood occurred at the minimum q values among those considered. A model with no prior on survey catchability has the $q$ estimated at the lower bound of $log(q) = -2$ (Figure \ref{fig:request6_prior_comparisons}).

\item[Request 7: Catch streams for the decision table should be as follows:] \hfill\\

\begin{enumerate}[(a)]\bfseries

\item Assume the 2017-2018 average total catch for 2019 and 2020 catches
\item Low catch stream: 250 mt/year
\item The default harvest control rule: 494 mt/year
\item High catch stream: ACL = ABC (P* = 0.45)
\item Use the category 2 sigma schedule recommended by the SSC (see Table 3 of the March SSC Report)

\end{enumerate}

\vspace{.4cm}

\textbf{Rationale:} To define the removal assumptions in the decision table.

\vspace{.4cm}

\textbf{STAT Response:}

Based on the discussion in the review, the following steps were taken to develop the states of nature and the decision table. Catchability of the WCGBT Survey was used as the axis of uncertainty. The new base model estimate has $q = 0.668$, $log(q) = -0.403$, with the standard deviation of 0.315 for the estimated $log(q)$ parameter. Using the formula of 1.15 units of standard deviation (provided in the terms of reference) to get low and high values leads to $log(q) = -0.766$ and $log(q) = -0.041$, corresponding to catchability values of $q = 0.465$, and $q = 0.960$. The high $q$ value was associated with a low state of nature which was near the 25% quantile of the 2019 spawning biomass estimate from the base model, which was perceived as too similar to the mean (where 12.5% and 87.5% quantiles were desired). A model with $log(q) = 0.223$, $q = 1.250$ (already run as part of the profile over $q$ was a better match to the 12.5% quantile in 2019 spawning biomass and chosen as the low state of nature. The high state with $q = 0.465$ was similar to the 87.5% quantile so was retained.

The time series of spawning biomass and distribution of estimated 2019 spawning biomass were provided to the panel (Figures \ref{fig:states_spawnbio} and \ref{fig:states_spawnbio_2019}).

\end{description}

<!-- *********************MODEL 1 RESULTS********************************** -->

## Base Case Model Results 

The base model parameter estimates and their approximate asymptotic standard errors 
are shown in Table \ref{tab:model_params}.  Estimates of derived reference points and 
approximate 95% asymptotic confidence intervals are shown in Table \ref{tab:Ref_pts_mod1V2}.
Time-series of estimated stock size over time are shown in Table \ref{tab:Timeseries_mod1}.

### Parameter Estimates

Values of all estimated parameters are provided in Table \ref{tab:model_params}. A few key parameters of note include natural mortality estimated at 0.445, slightly above the 0.36 median of the prior and with much narrower uncertainty than the prior (Figure \ref{fig:fit_to_priors}). $L_\infty$ was estimated at 175.67 for females and 120.97 for males (based on an exponential offset of -0.373). The $log(R_0)$ parameter was estimated at 8.728, corresponding to an unfished equilibrium recruitment of 6.18 million.

Catchability from the WCGBT Survey was estimated at 0.81, close the median of the prior applied to this parameter, with uncertainty estimated as very similar to the uncertainty in the prior (Figure \ref{fig:fit_to_priors}).

Selectivity was estimated to be asymptotic for the WCGBT Survey (the only fleet for which it was allowed to be dome-shaped), with the peak selectivity occurring at 76 cm, below the peak of the fishery selectivity at 94 cm (Figure \ref{fig:sel01_multiple_fleets_length1}). These two fleets had a similar estimate for the lower maximum selectivity for females than males, at 0.696 for the survey and 0.744 for the fishery. Selectivity for the Triennial survey was substantially different from the other two, with an additional parameter estimated for the initial selectivity of the smallest sizes necessary to fit the very flat length compositions from the two years of data available, and with a peak occurring at 188 cm, far higher than the other two curves. When converted to age, the selectivity peaked at about age-4 for the WCGBT Survey, age-5 for the fishery, and ages 7 and 12 for males and females in the Triennial Survey, respectively (Figure \ref{fig:sel02_multiple_fleets_age2}).

The length at 50% retention was estimated to be 66 cm, which is similar to the length at 50% selectivity, but the slope of the retention function was steeper. Thus, the fish that were discarded were primarily those sizes that were not fully selected (Figure \ref{fig:sel09_len_flt1sex1}). The asymptotic retention rate increased from 2004 to 2008 with a peak at close to 100%, followed by a decreasing trend from 2012 onward (Figure \ref{fig:retention}).

### Fits to the Data

<!-- Model fits to the indices of abundance, fishery length composition, survey length  -->
<!-- composition, discard rates, mean body weight, and conditional age-at-length observations are all discussed below.   -->

_Indices._
The observed indices show much more variability than the model expectation, with the fit to the WCGBT Survey essentially a flat line (Figure \ref{fig:index2_cpuefit_WCGBTS}).  The fit to the Triennial Survey shows a noticeable change over time due to the separate catchability parameters estimated for the early and late periods (Figure \ref{fig:index2_cpuefit_Triennial}).

_Length Data._
The fits to the length data were reasonably good (Figures \ref{fig:comp_lenfit_aggregated_across_time}--\ref{fig:comp_lenfit__multi-fleet_comparison} and \ref{fig:comp_lenfit_flt1mkt2}--\ref{fig:mod1_4_comp_lenfit_flt6mkt0}). The observed length compositions for males in both the fishery and the WCGBT Survey is bimodal, with modes in the 80 cm and 115 cm length bins for the fishery, and in the 60 cm and 115 cm bins for the survey. The model expectation has modes in similar locations in both cases, where the first mode is close to the estimated peak selectivity value and the second is close to the estimated male L-infinity parameter. However, the second mode in the model expectation is less pronounced than in the observed data (Figure \ref{fig:comp_lenfit_aggregated_across_time}). The residual patterns in the fit to the length compositions don't show strong patterns, with the WCGBT Survey data especially well fit. There are a few large residuals over a range of lengths in the early years as well as a few years where there were observations of small (under 50 cm) fish in the retained fishery catch which the model expected would have been discarded (Figure \ref{fig:comp_lenfit__multi-fleet_comparison}). The fit to the length data in alternative models that lacked either the growth cessation model or the sex-specific offsets to selectivity were less good (results not shown).

_Conditional Age-at-Length._
The conditional age-at-length data is likewise fit reasonably well, with some patterns in residuals showing variability among years, but no clear pattern that is consistent across years (Figures \ref{fig:age_fit_fishery} and \ref{fig:age_fit_WCGBTS}).

_Sex Ratios._
Sex ratio data is not included in the likelihood as such, but as a part of the length composition likelihood. The proportions of females and males are compiled into a single vector that is  compared to the model expectations in the multinomial likelihood. The patterns in sex ratio by length bin show fewer females than males for the middle range of sizes (70--120 cm), with a shift to almost 100% females for the largest size bins (over 130 cm). These patterns are shown in Figures \ref{fig:sexratio_len_flt1mkt2} and \ref{fig:sexratio_len_flt5mkt0}. The approximate uncertainty associated with the observed ratios is represented by a Jeffreys interval [@brown2001interval] based on the combination of the proportion of the lengths with each length bin and the adjusted input sample size. The use of sex-specific growth curves was adequate to fit the ratios for the largest bins, but ratio skews toward males at lengths where the mean ages are similar for females and males. The fit to this part of the sex ratio pattern required an offset in selectivity.

_Discards Rates and Mean Weight of the Discards._
Fit to the discard fraction estimates (Figure \ref{fig:discard_fitFishery}) and the mean weight of the discards (Figure \ref{fig:bodywt_fit_fltFishery}) show reasonably good fits. The model expectation is able to match the trend of decreasing discard fractions and decreasing mean weights over the years 2002--2010 by estimating an increasing trend in the asymptotic retention rate from 2004 to 2008 with a peak at close to 100%, followed by a decreasing trend from 2012 onward (Figures \ref{fig:sel09_len_flt1sex1} and \ref{fig:retention}). The years 2008--2012 with the highest asymptotic retention rates have little retention of large fish leading to lower discard rates and smaller mean weight of the discarded fish. The period from 2011 onward had observer coverage increased to 100% for the catch-shares trawl fishery, leading to more precise data and consistent patterns in the two data types. The first few years (which form the basis for the estimates going back to 1995), are more uncertain and less well fit, with the discard rates over 30%.  This is  inconsistent with the mean weight under 1.5 kg in 2003 and 2004.


### Uncertainty and Sensitivity Analyses

A number of sensitivity analyses were conducted, including:

\begin{itemize}

  \item Sensitivities to assumptions about selectivity and catchability

  \begin{itemize}

        \item Allowing all selectivity curves to be dome-shaped

        \item Removing the sex-specific offset on the selectivity curves
  
        \item Removing the prior on catchability for the WCGBT Survey

        \item Estimating a single catchability for all years in the Triennial Survey

  \end{itemize}

  \item Sensitivities to assumptions about biology
  
  \begin{itemize}

	\item Estimating separate natural mortality parameters for males and females
	
	\item Removing the prior on natural mortality
	
	\item Using the von Bertalanffy growth model
	
	\item Using the Richards growth model

  \end{itemize}

  \item Sensitivities to data weighting and recruitment

  \begin{itemize}

        \item Tuning the sample sizes using the McAllister-Ianelli method

        \item Tuning the sample sizes using the Dirichlet-Multinomial likelihood

        \item Removing the extra standard deviation parameter added to the index uncertainty
        \item Estimating recruitment deviations around the stock-recuit curve

  \end{itemize}

  \item Sensitivities to historical catch and discards

  \begin{itemize}

	\item Estimating historical discards based on 3yr average of discard rates and landings
	
	\item Changing discard mortality from 0.5 to 0.4
	
	\item Changing discard mortality from 0.5 to 0.6
	
	\item Adjusting historical catch by estimating multipliers on discards over blocks of time

	\item Adjusting historical catch to match a time series of fishing mortality for Petrale Sole

  \end{itemize}

\end{itemize}

Results of these sensitivities are shown in Figures \ref{fig:Sensitivity_sel_and_Q} to \ref{fig:Sensitivity_catch}, and Tables \ref{tab:Sensitivity_sel_and_Q} to \ref{tab:Sensitivity_catch}. More detailed descriptions of each group of sensitivities is provided below.

**Selectivity and catchability (Figure \ref{fig:Sensitivity_sel_and_Q} and Table \ref{tab:Sensitivity_sel_and_Q})**

Allowing the selectivity for all fleets to be dome-shaped resulted in domed selectivity for all fleets, but only improved the total negative log-likelihood by 0.9 units, mostly through a slightly improved fit to the length compositions, although the fit to the surveys was slightly worse (Table \ref{tab:Sensitivity_sel_and_Q}). Removing the offset between female and male selectivity caused the negative log-likelihood to be worse by 18.1 units, mostly through a worse fit to the length comps but also a worse fit to the conditional age-at-length compositions. The conditional age data was represented independently for each sex, so no sex-ratio information was present in the data, but the growth curves were changed slightly to compensate for the change in fit to the length data, resulting in a poorer fit to the age data as well. The scale of the population remained somewhat similar to the base model under both of these sensitivities (Figure \ref{fig:Sensitivity_sel_and_Q}).

Removing the prior on catchability for the WCGBT Survey had a large change in the estimated scale of the population, with the unfished equilibrium biomass increasing from the 2,224 mt estimated in the base model to 9,932 mt ("Q no prior on WCGBTS" in Figure \ref{fig:Sensitivity_sel_and_Q} and Table \ref{tab:Sensitivity_sel_and_Q}). However, the change in likelihood was relatively small, with the total improving by 0.4 units, of which 0.04 was associated with the prior itself.

**Biology (Figure \ref{fig:Sensitivity_bio} and Table \ref{tab:Sensitivity_bio})**

The sensitivity analyses related to biology and data weighting included assumptions about natural mortality ($M$), growth, and data weighting (Figure \ref{fig:Sensitivity_bio} and Table \ref{tab:Sensitivity_bio}). Allowing separate estimates of female and male natural mortality led to estimates of 0.475 for females and 0.395 for males, which are nearly symmetric around the 0.445 estimate of the shared mortality parameter in the base model. This difference allows more males to be present in the population and therefore better matches the skewed sex ratios in the length composition data. The scale of the unfished equilibrium spawning biomass dropped to 61% of the base model estimate due to the smaller fraction of females living to maturity with the higher $M$, but the estimate of total biomass in the unfished population remained at 91% of the base model (Table \ref{tab:Sensitivity_bio}). The improvement in likelihood is 2.2 units, which is modest given the extra parameter estimated. Additional explorations (not shown) indicated that a model with differential $M$ and no sex-specific offsets on the selectivity had much poorer fit to the data than either the base model or this sensitivity analysis. Therefore, given that the differential selectivity provided a greater improvement in model fit than the sex-specific $M$, only the more influential factor was included in the base model.

Removing the prior on $M$ had little impact on the model with $M$ increasing from 0.445 in the base model to 0.448 without the prior.

The use of either von Bertalanffy [-@VonB] or Richards [-@richards1959flexible] growth models provided poorer fits to both the conditional age-at-length and length data, and higher estimated variability in length-at-age (Figure \ref{fig:growth_curve_comparison}). The increase in variability in length-at-age suggests that the model is using this variability to compensate for lack of fit to the mean length-at-age. The Richards model is a generalization of the von Bertalanffy growth model with an additional parameter allowing a more sigmoidal shape. For females, this additional parameter was hitting the lower bound of 0.1 resulting in linear growth up to age 20. This parameter on the bound led to a bad gradient and a non-positive-definite Hessian matrix, indicated that the model had not converged to the maximum likelihood estimates. In theory, the additional parameter in the Richards model should always allow it to  provide a better likelihood relative to the von Bertalanffy, but further attempts to search for a converged model with Richards growth have not yet been undertaken.

**Data weighting and recruitment (Figure \ref{fig:Sensitivity_misc} and Table \ref{tab:Sensitivity_misc})**

The base model sample size adjustments from the Francis [-@Francis2011] method for the length composition data were 0.240 for the fishery lengths, 0.067 for the WCGBT Survey lengths, and 1.0 for the Triennial Survey lengths (constrained to avoid upweighting as the input sample size was already the number of fish for this one source). The sample size adjustments for the age data were 0.084 for the fishery and 0.054 for the WCGBT Survey. Tuning the sample sizes using the McAllister-Ianelli [-@McAllister1997] method had a relatively small impact on the model results (Figure \ref{fig:Sensitivity_misc} and Table \ref{tab:Sensitivity_misc}), with a lower weight given to the fishery lengths (0.107) than the status-quo Francis tuning method, and a higher weight given to the WCGBT Survey lengths (0.637). The lengths from the Triennial Survey were given similar weight. Ages from both the fishery and the WCGBT Survey were increased to 0.410 and 0.404, respectively. The likelihoods could not be compared due to these changes in the adjusted sample sizes, but the estimated parameters were all relatively similar to those in the base model. Tuning the sample sizes using the Dirichlet-Multinomial likelihood [-@Thorson2017c] resulting in higher weights for all length and age data, with sample size adjustments between 0.97 and 1.0 for all of the input length and age data. The scale of the spawning biomass increased with the Dirichlet-Multinomial likelihood (Figure \ref{fig:Sensitivity_misc} and Table \ref{tab:Sensitivity_misc}). Given the relatively good fit of the base model to the length and age data compared to the other inputs, especially the indices, the alternative data-weigthing methods, which in general increased the weight on these composition data, did not seem justified.

**Catch and discards (Figure \ref{fig:Sensitivity_catch} and Table \ref{tab:Sensitivity_catch})**

The sensitivity analyses related to discard mortality resulted in little change in the scale of the population for any scenario (Figure \ref{fig:Sensitivity_catch} and Table \ref{tab:Sensitivity_catch}). Increasing or decreasing the discard mortality from 0.5 to 0.4 or 0.6 had the least impact, while the two alternative time series of discards caused the population to fall to a lower level around 1990 and increase faster in the recent period. The discards based on 3-yr average analysis simply used the alternative time series of historical discards described above and shown in Figure \ref{fig:discard_calculations}.

The sensitivity analysis in which historical catch was adjusted by estimating multipliers on discards over blocks of time made use of the relatively new "catch multiplier" option in Stock Synthesis. Multiplier parameters controlling the ratio of the discards removed from the model relative to the input values were estimated for blocks of time covering the periods 1916--1949, 1950--1959, 1960--1969, 1970--1979, 1980--1989, and 1990--1994. These multiplier parameters were bounded to keep the input catch relative to the estimated total within the range 0.5--1.5 and a weak Beta prior distribution spanning this range was applied to the parameters to keep them from hitting the bounds and cause them to remain at 1.0 in the absence of information in the data.

The resulting pattern of historical discards shows a steadily increasing catch, with higher catch relative to the input values in all the blocks up to a peak in the 1980s, followed by a decrease in the estimated catch for the 1990-1994 period (Figures \ref{fig:adjusted_historic_catch_comparison} and \ref{fig:catch_multiplier_catch_comparison}). These changes provide a greater contrast in the catch history, causing the estimated time series of spawning biomass to fall to a lower level and then increase faster from the 1990s onward, thus fitting the WCGBT Survey slightly better (Figures \ref{fig:Sensitivity_catch} and {fig:Sensitivity_catch2}). However, the improvement in likelihood for the survey was only 0.3 units (Table \ref{tab:Sensitivity_catch}).

The sensitivity analysis in which historical catch was adjusted to match a time series of fishing mortality for Petrale Sole for the period 1950--1994 was based on the premise that fishing mortality for Petrale Sole is correlated with that for Big Skate. Petrale Sole frequently co-occur with Big Skate in both the fishery and survey [@Wallace2019]. Whereas the Dover Sole population used in the estimation of Longnose Skate discards has been very stable with %unfished never estimated as having falled below 63% of $B_0$, Petrale Sole was overfished for decades and the most recent stock assessment [@Stawitz2015] estimated that the spawning biomass fell to 5% of the unfished level by 1993 before subsequently rebuilding to about 30% of unfished biomass. Therefore, total catch of Petrale Sole is reflective of both the fishing mortality and the change in biomass over time. An additional complexity is that while the summer fishing grounds for Petrale are in relatively shallow water, there is also a winter fishery on Petrale Sole spawning aggregations in deeper water where Big Skate are likely less common. 

In the Petrale Sole stock assessment, the fishery was divded into separate Summer and Winter components and further divided between northern and southern areas, with the dividing line at 42 degrees N latitude (the boundary between Oregon and California). To develop an index of fishing mortality, a weighted average of the estimated $F$ time series for each of the two Summer fisheries was calculated by applying weights of 0.424 to the $F$ from the southern area and 0.576 for the northern area. These weights were based on the average ratio of estimated Big Skate biomass in the WCGBT Survey north and south of 42 degrees as estimated in the VAST index standardization. The resulting time series of Petrale Sole $F$ was then input to the Big Skate model as an index of $F$ for the historical fishery. As this index applied to the combination of both discarded and retained catch, those two components of the historical fishery were combined. The input catch values were treated as uncertain and the likelihood weight given to the index of $F$ was set high enough to ensure that the $F$ time series was matched exactly. The $F$ time series was fit for the years 1950--1994. Attempts to include the years prior to 1950 in the fit led to models that did not converge. 

The resulting estimates of $F$ and catch for Big Skate from this sensitivity analysis were somewhat similar to those derived from the catch multiplier sensitivity analysis described above, with higher mortality and catch in the 1970s and 1980s than in the 1950s (Figures \ref{fig:F_comparison} and \ref{fig:adjusted_historic_catch_comparison}). The resulting time series of spawning biomass started slightly above the base model and ended in a very similar place. To explore the impact of the catchability prior on this sensitivity analysis, an additional model run (not shown) was conducted with the prior turned off, which resulted in the estimated catchability value decreasing only slightly from $q = 0.828$ to $q = 0.815$, compared to the base model estimate of $q = 0.811$.

### Retrospective Analysis

Retrospective analyses, in which the final 5 years of data are successively removed from the model, showed relatively little change in the scale of the estimated population, but the uncertainty about the population size increased (Figure \ref{fig:retro}). The WCGBT Survey observations were underfit for the final 5 years, so removing these points, combined with a prior on catchability lowers the status of the stock, and led to a slightly reduced estimated spawning biomass.

### Likelihood Profiles

Likelihood profiles were conducted over the parameter controlling unfished equilibrium recruitment $log(R_0)$, catchability of the WCGBT Survey ($q$), stock-recruit steepness ($h$) and natural mortality ($M$). Results of these profiles are shown in Figures \ref{fig:profile_logR0} to \ref{fig:profile_M_compare1_spawnbio}. The contribution of different data sources to the changes in likelihood within the profiles were considered in the context of a change of less than 1.92 units of negative log-likelihood, sometimes considered small, based on half of the 95% quantile of a Chi-squared distribution with 1 degree of freedom.

The profile over $log(R_0)$ shows that the change in likelihood over a broad range of values is relatively small compared to models with more contrast in the data, with a total change in likelihood of less than 4 units over a range of 8.2 to 9.6, corresponding to a range in equilibrium recruitment of 3.6 million to 14.8 million (the $log(R_0)$ parameter is the log of $R_0$ in thousands). Models with $log(R_0) < 8.2$ did not converge. The age data and discard data are best fit at the highest $R_0$ considered while the index and mean body weight data are best fit at the lowest $R_0$. Only the priors and the length data are best fit at intermediate values. The length data was best fit at $log(R_0) = 8.6$, while the separate components of the prior likelihood were also best fit at $log(R_0) = 8.6$ in the case of the prior on the catchability of the WCGBT Survey, and at $log(R_0) = 8.2$ in the case of the prior on natural mortality. The base model estimate balancing all these components was $log(R_0) = 8.728$. The spawning biomass estimates from the models in the profile were all relatively similar as a result of the models with higher $R_0$ also having a higher $M$ estimate, leading to a similar number of fish surviving to maturity (the range was $M = 0.526$ at $log(R_0) = 9.6$ to $M$ = 0.398$ at $log(R_0) = 8.2$).

The profile over catchability of the WCGBT Survey ($q$) provides a better illustration of the information in the data about the scale of the population, because the prior on $q$ is no longer influencing the estimates of all other parameters. The range considered for the parameter $log(q)$ corresponded to $q = 0.5$ to $q = 2.0$, where $q = 0.5$ has the observed survey biomass equal to half of the true population after accounting for selectivity of the survey, and $q = 2.0$ corresponds to the survey observations being double the true population. The likelihood contributions are represented here both without and with the prior likelihood (Figures \ref{fig:profile_logQ_noprior} and \ref{fig:profile_logQ}). The prior has a much stronger influence on the changes in likelihood over the range considered, with a total change of greater than 10 units of negative log-likelihood. The length data is the most influential of the other components, with a change of 2.6 units over the range of $q$ considered, with the best fit occurring at the smallest $q$ values. All three sources of length data were best fit at the lowest $q$ values with the fishery contributing 71% of the change, the WCGBT Survey 27% and the remaining %1 from the Triennial survey. The mean body weight data is also better fit at low $q$ while the indices and discard data are best fit at $q = 1.75$. The age data and the prior on natural mortality show very little change in likelihood over the range of $q$ considered (less than 0.1 unit of negative log-likelihood).

The spawning biomass estimated for the models included in the $q$ profile (Figure \ref{fig:profile_Q_compare1_spawnbio}) show similar trajectories, with the scale of the population negatively correlated with the $q$ values as expected.

The profile over steepness of the stock-recruit curve shows less than 0.8 units of likelihood over the range $h = 0.3$ to $h = 0.9$. The best fit occurred at $h = 0.5$, indicating that a model with steepness estimated would have been relatively similar to the base model where $h$ was fixed at 0.4. However, earlier explorations indicated that models with $h$ estimated sometimes produced unstable results, where small changes in model configuration could cause the parameter to be estimated at either the upper or lower bound of the 0.2--1.0 range on which it's defined for the Beverton-Holt stock-recruit curve.

The profile over natural mortality ($M$) shows that most of the information in the likelihood about $M$ was from the length and age data, with additional information in the discard rates and the mean body weight data. The prior on $M$ provided relatively little contribution to the total likelihood. The length data had the largest change in likelihood over the 0.25--0.55 range of $M$ considered, and was best fit at 0.45, close to the base model estimate of 0.445.

### Reference Points

Reference points were calculated using the estimated selectivities and catch distribution among fleets in the most recent year of the model, (`r LastYR`). Sustainable total yield (landings plus discards) were `r Ref_pts_mod1[15,2]` mt when using an $SPR_{50\%}$ reference harvest rate and with a 95% confidence interval of `r Ref_pts_mod1[15,3]` mt based on estimates of uncertainty. The spawning biomass equivalent to 40% of the unfished level ($SB_{40\%}$) was `r Ref_pts_mod1[7,2]` mt.

The `r LastYR+1` spawning biomass relative to unfished equilibrium spawning biomass is above the target of 40% of unfished levels (Figure \ref{fig:ts9_unfished_with_95_asymptotic_intervals_intervals}). The relative fishing intensity, $(1-SPR)/(1-SPR_{50\%})$, has been below the management target for the entire time series of the model (Table \ref{tab:Timeseries_mod1}).

Table \ref{tab:Ref_pts_mod1V2} shows the full suite of estimated reference points for the base model and Figure \ref{fig:yield1_yield_curve} shows the equilibrium curve based on a steepness value of 0.4.



