---
output:
  pdf_document: default
  html_document: default
---
<!-- ====================================================================== -->
<!-- ****************************            ****************************** --> 
<!-- ****************************BEGIN TABLES****************************** --> 
<!-- ****************************             ***************************** --> 
<!-- ======================================================================--> 

# Tables

## Data Tables

<!-- ********************************************************************** --> 
<!-- *********************Commercial landings TABLES*********************** --> 
<!-- ********************************************************************** --> 

```{r, results = 'asis'}

############### Reconstructed Landings by Source

Catch_by_State = read.csv("./txt_files/data_summaries/reconstructed_landings_by_state.csv")

caption = "Landings by source.  For detail on the source of the different estimates, see 'Fishery Landings and Discards' above. Values prior to 1939 were not included in the final model and augmented by an estimated linear increase in total catch including discards from 1916 to 1950. Estimated discards are not included in this table."

colnames(Catch_by_State) = c("Year","CA (mt)","OR (mt)","WA (mt)","Tribal (mt)","Total (mt)")

byState_catch.table = xtable(Catch_by_State, 
                             caption = caption,
                             label = 'tab:Reconstructed_Landings_byState')

addtorow          <- list()
addtorow$pos      <- list()
addtorow$pos[[1]] <- c(0)
addtorow$command  <- c(paste("\\hline \n",
                             "\\endhead \n",
                             "\\hline \n",
                             "\\multicolumn{3}{l}",
                             "{\\footnotesize Continued on next page} \n",
                             "\\endfoot \n",
                             "\\endlastfoot \n",sep=""))
# Print
print(byState_catch.table, 
      include.rownames = FALSE,
      floating = FALSE,
      caption.placement = 'top',
      tabular.environment = 'longtable',
      sanitize.colnames.function=function(x){x},
      add.to.row = addtorow)

```

     
     
*********************************


\FloatBarrier
\newpage

```{r, results = 'asis'}

Indices = read.csv("./txt_files/data_summaries/table_of_index_inputs.csv")

colnames(Indices) = c("Year","Obs","se_log","Obs","se_log","Obs","se_log")

a_header <- construct_header(
  # the data.frame or matrix that should be plotted
  Indices,
  # the labels of the groups that we want to insert
  grp_names = c("", "WCGBTS", "Triennial","IPHC"),
  # the number of columns each group spans
  span = c(1, 2, 2,2),
  # the alignment of each group, can be a single character (lcr) or a vector
  align = "c"
)

caption = "Index inputs considered for the assessment model. The IPHC index was not used in the final model. The WCGBT and Triennial Surveys were standardized using the VAST geostatistical software and are in units of metric tons. The IPHC index is in units of fish per 1000 hooks."

index.table = xtable(Indices,
                    caption = caption,
                    label = 'tab:index_inputs')

 align(index.table) = c('l', 'l',
                               '>{\\centering}p{0.6in}',
                               '>{\\centering}p{0.6in}',
                               '>{\\centering}p{0.6in}',
                               '>{\\centering}p{0.6in}',
                               '>{\\centering}p{0.6in}',
                               '>{\\centering}p{0.6in}')


print(index.table, add.to.row = a_header, 
      caption.placement = "top", 
      include.rownames = F, hline.after = F)


```


\FloatBarrier
\newpage


```{r, results = 'asis'}

PacFIN = read.csv("./txt_files/data_summaries/PacFIN.sample_sizes_by_state_with_ages.csv")

colnames(PacFIN) = c("Year", rep(c("Ntows","Nfish"),5))

a_header <- construct_header(
  # the data.frame or matrix that should be plotted
  PacFIN,
  # the labels of the groups that we want to insert
  grp_names = c("", "CA","OR","WA","All Landings","Discards"),
  # the number of columns each group spans
  span = c(1, 2,2,2,2,2),
  # the alignment of each group, can be a single character (lcr) or a vector
  align = "c"
)


caption = "PacFIN length and age sample sizes by year and state with the number of unique tows from which Big Skate were sampled as well as the number of individual Big Skates that were measured." Samples from all landings were combined for the fishery length and age compositions, while samples from discards were treated separately.

PacFIN.table = xtable(PacFIN,
                             caption = caption,
                             label = 'tab:PacFIN_Samples')


print(PacFIN.table, add.to.row = a_header, 
      caption.placement = "top", 
      include.rownames = F, hline.after = F)
```





\FloatBarrier
\newpage

```{r, results = 'asis'}

SurveySamples = read.csv("./txt_files/data_summaries/survey_sample_sizes.csv", as.is=T)

colnames(SurveySamples) = SurveySamples[1,]
SurveySamples = SurveySamples[-1,]

caption = "Survey length and age sample sizes by year with the number of unique tows or sets from which Big Skate were sampled as well as the number of individual Big Skates that were measured."

a_header <- construct_header(
  # the data.frame or matrix that should be plotted
  SurveySamples,
  # the labels of the groups that we want to insert
  grp_names = c("", "Triennial","WCGBTS","IPHC"),
  # the number of columns each group spans
  span = c(1, 2,2,2),
  # the alignment of each group, can be a single character (lcr) or a vector
  align = "c"
)

SurveySamples.table = xtable(SurveySamples,
                             caption = caption,
                             label = 'tab:Survey_Samples')

print(SurveySamples.table, add.to.row = a_header, 
      caption.placement = "top", 
      include.rownames = F, hline.after = F)

```





\FloatBarrier
\newpage

<!-- ********************************************************************** --> 
<!-- ***********Recreational Landings and discards TABLE******************* --> 
<!-- ********************************************************************** --> 
<!-- Washington rec removal TABLES--> 


<!-- Oregon rec removal TABLES-->


<!-- California rec removal TABLES-->

\newpage
\FloatBarrier
<!-- ********************************************************************** --> 
<!-- *****Fleet xx index TABLES******* -->
<!-- ********************************************************************** --> 



\FloatBarrier
<!-- ********************************************************************** -->
<!-- *****Fleet xx index TABLES******* -->
<!-- ********************************************************************** -->


\FloatBarrier
<!-- ********************************************************************** -->
<!-- *****Fleet xx index TABLES******* -->
<!-- ********************************************************************** -->









\FloatBarrier
<!-- ********************************************************************** -->
<!-- *****Fleet xx index TABLES******* -->
<!-- ********************************************************************** -->




