
## Model Results Tables

\FloatBarrier

<!-- ====================================================================== -->
<!-- ********************BASE-CASE MODEL 1 TABLES************************** --> 
<!-- **REPEAT THIS SECTION AND EDIT AS NEEDED IF YOU HAVE MULTIPLE MODELS** --> 
<!-- ====================================================================== -->

\FloatBarrier


<!-- ***********MODEL 1 REFERENCE POINTS TIME SERIES TABLE***************** --> 

```{r}
    # Total biomass, extract and subset
    Bio_all = mod1$timeseries[, c('Yr', 'Bio_all')]
    Bio_allyrs = subset(Bio_all, Yr > (Dat_start_mod1 - 1) & Yr <= (LastYR + 1))

  
  
    # Spawning biomass, extract and subset, and turn into scientific notation
    SpawningB = mod1$derived_quants[grep('SSB', mod1$derived_quants$Label), ]
    SpawningB = SpawningB[c(-1, -2), ]
    SpawningByrs = SpawningB[SpawningB$Label >= paste('SSB_', Dat_start_mod1, sep='') &  
                             SpawningB$Label <= paste('SSB_', LastYR + 1, sep=''), ] 
        
        SpawningB_units = ''
        if(mean(SpawningByrs$Value) > 1000000){
            SpawningB_units <- "million"
            SpawningByrs$Value <- SpawningByrs$Value/1000000
         }

    
    # Depletion, extract, rename and subset
    Depl_years = as.data.frame(seq(Dat_start_mod1, LastYR + 1, 1))
    colnames(Depl_years) = 'Yr'
    Depl_years$Depl = 0
    Depletion = mod1$derived_quants[grep('Bratio', mod1$derived_quants$Label), ]
    Depletionyrs = Depletion[Depletion$Label >= paste0('Bratio_', Dat_start_mod1) &  
                             Depletion$Label <= paste0('Bratio_', LastYR + 1), ]
    
    Depletionyrs$Yr = Depletionyrs$Label1 = substr(Depletionyrs$Label,
                                                     (nchar(Depletionyrs$Label) + 1) - 4, 
                                                      nchar(Depletionyrs$Label))
   # Make sure depletion is numeric and merge ...
   Depletionyrs$Yr = as.numeric(Depletionyrs$Yr)
   Depleteyrs = merge(Depl_years, Depletionyrs, all.x=T, all.y=T, by.x='Yr', by.y='Yr')
   Depleteyrs[is.na(Depleteyrs)] <- 0
   Depleteyrs$total = Depleteyrs$Depl + Depleteyrs$Value
    
   # Recruits, extract and subset
   Recruit = mod1$derived_quants[grep('Recr', mod1$derived_quants$Label), ]
   Recruit = Recruit[c(-1, -2), ]
   Recruityrs = Recruit[Recruit$Label >= paste('Recr_', Dat_start_mod1, sep='') &  
                        Recruit$Label <= paste('Recr_', LastYR + 1, sep=''), ]  
    
    
   # Landings/total catch, extract and subset years
   Landings = mod1$sprseries[ , c('Yr','Dead_Catch_B')]
   Landingsyrs = subset(Landings, Yr > (Dat_start_mod1 - 1) & Yr <= (LastYR + 1))
    
  
    
   # Relatvie exploitation rate, extract, subset and merge
   Exploit = mod1$derived_quants[grep('F', mod1$derived_quants$Label), ]
   Exploit = Exploit[c(-1, -2), ]
   Exploityrs = Exploit[Exploit$Label >= paste('F_', Dat_start_mod1, sep = '') &  
                        Exploit$Label <= paste('F_', LastYR + 1, sep = ''), ]  
   Exploityrs$Yr = Exploityrs$Label1 = substr(Exploityrs$Label, 
                                               (nchar(Exploityrs$Label) + 1) - 4,
                                                nchar(Exploityrs$Label))
   Exploityrs$Yr = as.numeric(Exploityrs$Yr)
   Exploited = merge(Depl_years, Exploityrs, all.x=T, all.y=T, by.x='Yr', by.y='Yr')
   Exploited[is.na(Exploited)] <- 0
   Exploited$total = Exploited$Depl + Exploited$Value
    
  # SPR, extract and subset years
  SPR = mod1$sprseries[, c('Yr', 'SPR')]
  SPRyrs = subset(SPR, Yr > (Dat_start_mod1 - 1) & Yr <= (LastYR + 1))
  
  # fix %unfished values for first years
  for(irow in 1:2){
    if(Depleteyrs$total[irow] == 0){
      Depleteyrs$total[irow] <- 1.0
    }
  }
  
  # Bind all the columns together for the table
  Timeseries = as.data.frame(cbind(seq(Dat_start_mod1, LastYR + 1, 1), 
                                       Bio_allyrs$Bio_all, 
                                       SpawningByrs$Value,
                                       Depleteyrs$total,
                                       Recruityrs$Value, 
                                       Landingsyrs$Dead_Catch_B, 
                                       Exploited$total,
                                       SPRyrs$SPR))

 # Add colulmn names    
 colnames(Timeseries)=c('Yr', 
                        'Total biomass (mt)', 
                        paste0('Spawning biomass', SpawningB_units, ' (mt)'),
                        'Fraction unfished', 
                        'Age-0 recruits', 
                        'Total catch (mt)',
                        'Relative exploitation rate', 
                        'SPR')
 
 # Make year a factor so you don't have a decimal   
 Timeseries$Yr = as.factor(Timeseries$Yr)
    
 # Remove 2015 values for last three columns since year isn't complete
 Timeseries[nrow(Timeseries), c((ncol(Timeseries) - 2):ncol(Timeseries))] <- NA
```

```{r, results='asis'}
    # Create the time series table
    Timeseries1 = Timeseries
    colnames(Timeseries1)[1] = 'Year'
    Timeseries.table = xtable(Timeseries1, 
                              caption = c('Time-series of population estimates 
                                        from the base-case model. Relative exploitation 
                                        rate is $(1-SPR)/(1-SPR_{50\\%})$.'),
                              label='tab:Timeseries_mod1',
                              digits = c(0,0,0,0,3,0,0,2,2))   

    # Add alignment
    align(Timeseries.table) = c('l',
                                'c',
                                '>{\\centering}p{.6in}',
                                '>{\\centering}p{.6in}',
                                '>{\\centering}p{.6in}',
                                '>{\\centering}p{.6in}',
                                '>{\\centering}p{.8in}',
                                '>{\\centering}p{.8in}',
                                'c')
    
    addtorow          <- list()
    addtorow$pos      <- list()
    addtorow$pos[[1]] <- c(0)
    addtorow$command  <- c(paste("\\hline \n",
                                 "\\endhead \n",
                                 "\\hline \n",
                                 "\\multicolumn{5}{l}",
                                 "{\\footnotesize Continued on next page} \n",
                                 "\\endfoot \n",
                                 "\\endlastfoot \n",sep=""))
    
    
    # add.to.row$command  =  paste("\\hline  \\endfirsthead",  # First caption
    #                              "\\caption[]{Time-series of population estimates 
    #                               from the base-case model. Relative exploitation 
    #                               rate is $(1-SPR)/(1-SPR_{50\\%})$.} \\label{tab:Timeseries_mod1} \\\\ \\hline", # Addit. captions
    #                              paste(colnames(Timeseries1)[1], paste("&", colnames(Timeseries1)[2:8], collapse=" ")), # Column names
    #                              "\\\\ \\hline ",
    #                              "\\endhead", 
    #                              "\\hline \\multicolumn{5}{l}{\\textit{Continues next page}} \\ 
    #                              \\endfoot
    #                              \\endlastfoot",
    #                              collapse=" ")
    
    
    
               # Print timeseries of population estimates table
               print(Timeseries.table, 
                     include.rownames=FALSE,      
                     caption.placement="top",
                     align=TRUE,
                     tabular.environment="longtable",
                     floating=FALSE,  
                     #sanitize.text.function = function(x){x},
                     add.to.row = addtorow)
               
```
<!-- ---------------------------------------------------------------------- -->

<!-- ***********MODEL 1 PARAMETERS***************************************** --> 
<!-- ***********Estimated and Fixed Parameters***************************** --> 

\begin{landscape}
```{r, results='asis'}
       # If you use this for more than one model = change mod1 to mod2 or mod3
    mod_params = mod1$parameters[-c(grep('Recr',mod1$parameters$Label),
                                         grep('Impl',mod1$parameters$Label)),
                                      (names(mod1$parameters) %in%
                                         c("Num","Label","Value","Phase","Min",
                                           "Max","Status","Parm_StDev",
                                           "Pr_type","Prior","Pr_SD"))]  

    # replace some parameter labels
    mod_params$Label <- gsub(pattern = "Cessation",
                             replacement = "Cessation_slope",
                             x = mod_params$Label)
    mod_params$Label <- gsub(pattern = "VonBert_K",
                             replacement = "Cessation_age",
                             x = mod_params$Label)

    # Combine bounds into one column
    mod_params$Min = paste('(', mod_params$Min, ', ', mod_params$Max, ')', sep='')
    
    
    # Combine prior info to one column
    #mod_params$Pr_type = gsub('No_prior', 'None', mod_params$Pr_type)
    mod_params$Pr_type = ifelse(mod_params$Pr_type == 'No_prior' , 'None',
                                paste(mod_params$Pr_type,' (', mod_params$Prior, 
                                      ', ', mod_params$Pr_SD, ')', sep = ''))
    
    # Remove the max, prior and prior sd columns
    drops = c('Max', 'Prior', 'Pr_SD')
    mod_params = mod_params[, !(names(mod_params) %in% drops)]
    
    # Add column names
    colnames(mod_params) = c('No.',
                             'Parameter',
                             'Value',
                             'Phase',
                             'Bounds',
                             'Status',
                             'SD',
                             'Prior (Exp.Val, SD) ')
    
    mod_params$Parameter = gsub("Fishery_current(1)_BLK2repl", "", mod_params$Parameter, fixed=T)
    
    mod_params$Parameter = gsub("Fishery_current", "", mod_params$Parameter, fixed=T)
    mod_params$Parameter = gsub("BLK1repl", "", mod_params$Parameter, fixed=T)


    # Model 1 model parameters
    mod_params.table = xtable(mod_params, 
                              caption=c(paste('List of parameters used in
                                              the base model, including estimated 
                                              values and standard deviations (SD), 
                                              bounds (minimum and maximum), 
                                              estimation phase (negative values indicate
                                              not estimated), status (indicates if 
                                              parameters are near bounds, and prior type
                                              information (mean, SD).'
                                              , sep='')), 
                              label='tab:model_params',
                              digits = c(0,0,0,3,0,3,0,3,0))  

    # Add alignment  
    align(mod_params.table) = c('l','l','p{2.5in}','l','r','c','c','c','l')
        
 
    # Add "continued on next page"" footnote   
    addtorow          <- list()
    addtorow$pos      <- list()
    addtorow$pos[[1]] <- c(0)
    addtorow$command  <- c(paste("\\hline \n",
                                 "\\endhead \n",
                                 "\\hline \n",
                                 "\\multicolumn{3}{l}",
                                 "{\\footnotesize Continued on next page} \n",
                                 "\\endfoot \n",
                                 "\\endlastfoot \n",sep=""))



    # Print Model 1 parameters
    print(mod_params.table, 
          include.rownames = FALSE,
          caption.placement = 'top',
          tabular.environment = 'longtable',
          floating = FALSE,
          add.to.row = addtorow)
```
\end{landscape}

\clearpage
<!-- ---------------------------------------------------------------------- -->

\FloatBarrier

<!-- ***********MODEL 1 Likelihood components******************************* --> 

<!-- IGT: Table removed on 5/14/2019, code available in earlier versions of this file --> 

<!-- *********** Sensitivity to Sel and Q ******************************* --> 

```{r, results = 'asis'}
    
    # Read in/organize sensitivity file, change column names, caption
    Sens_model1 = read.csv('./txt_files/Sensitivities_sel_and_Q.csv')
    colnames(Sens_model1) = c('Label', 
                              'Base',
                              'All selectivity domed',
                              'No sex-specific selectivity',
                              'Longnose Skate catchability prior',
                              'Remove catchability prior',
                              'No catchability change in Triennial')

    #colnames(Sens_model1) <- gsub(pattern=".", replacement=" ", x=colnames(Sens_model1), fixed=TRUE)
    
    # Create sensitivities table
    Sens_model1.table = xtable(Sens_model1, 
                               caption = c('Sensitivity of the base model 
                                          to assumptions about selectivity and
                                          catchability.
                                          Likelihood values are negative
                                          log-likelihood where smaller values
                                          indicate a better fit.'),
                               label = 'tab:Sensitivity_sel_and_Q', digits = 2)    
  
    # Add alignment - this uses centered aligment of .6 inches for all columns 2+,
    # You can change this easily to have variable columns width after you know how many
    # colunns your final table has
    align(Sens_model1.table) = c('l','l', rep('>{\\centering}p{.8in}', dim(Sens_model1)[2]-1))


    # Print model 1 sensitivity table
    print(Sens_model1.table, 
          include.rownames = FALSE,             
          caption.placement = 'top',
          #floating.environment = 'sidewaystable',
          scalebox = .9)

```

\FloatBarrier

\newpage


<!-- *********** Sensitivity to biology ******************************* --> 

```{r, results = 'asis'}
    
    # Read in/organize sensitivity file, change column names, caption
    Sens_model1 = read.csv('./txt_files/Sensitivities_bio.csv')
    colnames(Sens_model1) = c('Label', 
                              'Base',
                              'Sex-specific M',
                              'No prior on M',
                              'von B growth',
                              'Richards growth')

    #colnames(Sens_model1) <- gsub(pattern=".", replacement=" ", x=colnames(Sens_model1), fixed=TRUE)
    
    # Create sensitivities table
    Sens_model1.table = xtable(Sens_model1, 
                               caption = c('Sensitivity of the base model 
                                          to assumptions about biology.
                                          Likelihood values are negative
                                          log-likelihood where smaller values
                                          indicate a better fit.'),
                               label = 'tab:Sensitivity_bio', digits = 2)    
  
    # Add alignment - this uses centered aligment of .6 inches for all columns 2+,
    # You can change this easily to have variable columns width after you know how many
    # colunns your final table has
    align(Sens_model1.table) = c('l','l', rep('>{\\centering}p{.8in}', dim(Sens_model1)[2]-1))


    # Print model 1 sensitivity table
    print(Sens_model1.table, 
          include.rownames = FALSE,             
          caption.placement = 'top',
          #floating.environment = 'sidewaystable',
          scalebox = .9)

```

<!-- *********** Sensitivity to data weighting and recruitment ******************************* --> 

```{r, results = 'asis'}
    
    # Read in/organize sensitivity file, change column names, caption
    Sens_model1 = read.csv('./txt_files/Sensitivities_misc.csv')
    colnames(Sens_model1) = c('Label', 
                              'Base',
                              'McAllister-Ianelli tuning',
                              'Dirichlet-Multinomial tuning',
                              'No extra SD on indices',
                              'Estimate rec. devs.',
                              'Estimate rec. devs., no q prior'
                              )

    #colnames(Sens_model1) <- gsub(pattern=".", replacement=" ", x=colnames(Sens_model1), fixed=TRUE)
    
    # Create sensitivities table
    Sens_model1.table = xtable(Sens_model1, 
                               caption = c('Sensitivity of the base model 
                                          to assumptions about data weighting
                                          and recruitment. 
                                          Likelihood values are negative
                                          log-likelihood where smaller values
                                          indicate a better fit.'),
                               label = 'tab:Sensitivity_misc', digits = 2)    
  
    # Add alignment - this uses centered aligment of .6 inches for all columns 2+,
    # You can change this easily to have variable columns width after you know how many
    # colunns your final table has
    align(Sens_model1.table) = c('l','l', rep('>{\\centering}p{.8in}', dim(Sens_model1)[2]-1))


    # Print model 1 sensitivity table
    print(Sens_model1.table, 
          include.rownames = FALSE,             
          caption.placement = 'top',
          #floating.environment = 'sidewaystable',
          scalebox = .9)

```


<!-- *********** Sensitivity to catch ******************************* -->

```{r, results = 'asis'}
    
    # Read in/organize sensitivity file, change column names, caption
    Sens_model1 = read.csv('./txt_files/Sensitivities_catch.csv')
    colnames(Sens_model1) = c('Label', 
                              'Base',
                              'Discards based on 3yr-avg.',
                              'Discard mortality = 0.4',
                              'Discard mortality = 0.6',
                              'Multipliers on historic discards',
                              'Fit time series of F from Petrale')

    #colnames(Sens_model1) <- gsub(pattern=".", replacement=" ", x=colnames(Sens_model1), fixed=TRUE)
    
    # Create sensitivities table
    Sens_model1.table = xtable(Sens_model1, 
                               caption = c('Sensitivity of the base model 
                                          to assumptions about catches and discards.
                                          Likelihood values are negative
                                          log-likelihood where smaller values
                                          indicate a better fit..'),
                               label = 'tab:Sensitivity_catch', digits = 2)    
  
    # Add alignment - this uses centered aligment of .6 inches for all columns 2+,
    # You can change this easily to have variable columns width after you know how many
    # colunns your final table has
    align(Sens_model1.table) = c('l','l', rep('>{\\centering}p{.8in}', dim(Sens_model1)[2]-1))


    # Print model 1 sensitivity table
    print(Sens_model1.table, 
          include.rownames = FALSE,             
          caption.placement = 'top',
          #floating.environment = 'sidewaystable',
          scalebox = .9)

```

\FloatBarrier

\newpage

\FloatBarrier

\newpage

<!-- ********************MODEL 1 CONVERGENCE TABLE************************* --> 

<!-- ***********JITTER TABLE*********************************************** --> 

```{r, results = 'asis'}
    # Replace values in file and read in - values for all models in 1 table  
      jitter = read.csv('./txt_files/JitterTable.csv') 
      colnames(jitter) = c('Description',
                           'Value')

    # Create model 1 jitter table
    jitter.table = xtable(jitter, 
                          caption = c('Results from 100 jitters from the base 
                                      case model.'),
                          label = 'tab:jitter')
    
    # Print jitter table (all models)    
    print(jitter.table, 
          include.rownames = FALSE, 
          caption.placement = 'top')
```


<!-- ***********Retrospective table*********************************** -->
<!-- IGT: Table removed on 5/14/2019, code available in earlier versions of this file -->


<!-- ***********Likelihood profile table*********************************** -->
<!-- IGT: Table removed on 5/14/2019, code available in earlier versions of this file -->



<!-- ***********MODEL 1 HARVEST PROJECTIONS TABLE************************** --> 
\newpage
```{r, results = 'asis'}
    # Pull OFL contribution and subset years
    OFLcatch = mod1$derived_quants[grep('OFLCatch', mod1$derived_quants$Label), ]
    OFLcatchyrs = OFLcatch[OFLcatch$Label >= paste('OFLCatch_', Project_firstyr, sep = '') &
                           OFLcatch$Label <= paste('OFLCatch_', Project_lastyr, sep = ''), ]

    # Pull forecasted landings and subset years
    ForecastC = mod1$timeseries[, grepl('Yr|retain[(]B[)]', names(mod1$timeseries))]
    ForecastC$total = rowSums(ForecastC[, -1])
    ForecastCyrs = subset(ForecastC, Yr > (Project_firstyr - 1) & Yr < (Project_lastyr + 1))

    # Pull summary biomass and subset years
    Smry_biomass = mod1$timeseries[, c('Yr', 'Bio_smry')]
    Smry_biomassyrs = subset(Smry_biomass, Yr > (Project_firstyr - 1) & Yr < (Project_lastyr + 1))


    # Pull spawning biomass and subset years
    SpawningB = mod1$derived_quants[grep('SSB', mod1$derived_quants$Label), ]
    SpawningB = SpawningB[c(-1, -2), ]
    SpawningByrs = SpawningB[SpawningB$Label >= paste('SSB_', Project_firstyr, sep = '') &
                             SpawningB$Label <= paste('SSB_', Project_lastyr, sep = ''), ]

    # Pull depletion and subset years
    Depletion = mod1$derived_quants[grep('Bratio', mod1$derived_quants$Label), ]
    Depletion = Depletion[c(-1, -2), ]
    Depletionyrs = Depletion[Depletion$Label >= paste('Bratio_', Project_firstyr, sep = '') &
                             Depletion$Label <= paste('Bratio_', Project_lastyr, sep = ''), ]

    # Combine the data for the forecast table
    Forecast_mod1 = as.data.frame(cbind(seq(Project_firstyr, Project_lastyr, 1),
                                        OFLcatchyrs$Value,
                                        ForecastCyrs$total,
                                        Smry_biomassyrs$Bio_smry,
                                        SpawningByrs$Value,
                                        Depletionyrs$Value))
    # Add column names
    colnames(Forecast_mod1)=c('Yr',
                           'OFL contribution (mt)',
                           'ACL landings (mt)',
                           'Age 2+ biomass (mt)',
                           'Spawning Biomass (mt)',
                           'Depletion')

    # Make sure year is a factor, so you don't get decimals
    Forecast_mod1$Yr = as.factor(Forecast_mod1$Yr)

    # Create the forecast table
    Forecast_mod1.table = xtable(Forecast_mod1,
                              caption = c('Projection of potential
                                        OFL, spawning biomass, and depletion for the
                                        base case model.'),
                              label = 'tab:Forecast_mod1', digits = 3)
    # Add alignment
    align(Forecast_mod1.table) = c('l',
                                   'c',
                                   '>{\\centering}p{1in}',
                                   '>{\\centering}p{1in}',
                                   '>{\\centering}p{1in}',
                                   '>{\\centering}p{1in}',
                                   '>{\\centering}p{1in}')

    # Print model 1 forecast table
    print(Forecast_mod1.table,
          include.rownames = FALSE,
          caption.placement = 'top')
```
<!-- ---------------------------------------------------------------------- -->
\FloatBarrier


<!-- ***********MODEL 1 REFERENCE POINTS TIME SERIES TABLE***************** --> 

```{r}
    # Total biomass, extract and subset
    Bio_all = mod1$timeseries[, c('Yr', 'Bio_all')]
    Bio_allyrs = subset(Bio_all, Yr > (Dat_start_mod1 - 1) & Yr <= (LastYR + 1))

  
  
    # Spawning biomass, extract and subset, and turn into scientific notation
    SpawningB = mod1$derived_quants[grep('SSB', mod1$derived_quants$Label), ]
    SpawningB = SpawningB[c(-1, -2), ]
    SpawningByrs = SpawningB[SpawningB$Label >= paste('SSB_', Dat_start_mod1, sep='') &  
                             SpawningB$Label <= paste('SSB_', LastYR + 1, sep=''), ] 
        
        SpawningB_units = ''
        if(mean(SpawningByrs$Value) > 1000000){
            SpawningB_units <- "million"
            SpawningByrs$Value <- SpawningByrs$Value/1000000
         }

    
    # Depletion, extract, rename and subset
    Depl_years = as.data.frame(seq(Dat_start_mod1, LastYR + 1, 1))
    colnames(Depl_years) = 'Yr'
    Depl_years$Depl = 0
    Depletion = mod1$derived_quants[grep('Bratio', mod1$derived_quants$Label), ]
    Depletionyrs = Depletion[Depletion$Label >= paste0('Bratio_', Dat_start_mod1) &  
                             Depletion$Label <= paste0('Bratio_', LastYR + 1), ]
    
    Depletionyrs$Yr = Depletionyrs$Label1 = substr(Depletionyrs$Label,
                                                     (nchar(Depletionyrs$Label) + 1) - 4, 
                                                      nchar(Depletionyrs$Label))
   # Make sure depletion is numeric and merge ...
   Depletionyrs$Yr = as.numeric(Depletionyrs$Yr)
   Depleteyrs = merge(Depl_years, Depletionyrs, all.x=T, all.y=T, by.x='Yr', by.y='Yr')
   Depleteyrs[is.na(Depleteyrs)] <- 0
   Depleteyrs$total = Depleteyrs$Depl + Depleteyrs$Value
    
   # Recruits, extract and subset
   Recruit = mod1$derived_quants[grep('Recr', mod1$derived_quants$Label), ]
   Recruit = Recruit[c(-1, -2), ]
   Recruityrs = Recruit[Recruit$Label >= paste('Recr_', Dat_start_mod1, sep='') &  
                        Recruit$Label <= paste('Recr_', LastYR + 1, sep=''), ]  
    
    
   # Landings/total catch, extract and subset years
   Landings = mod1$sprseries[ , c('Yr','Dead_Catch_B')]
   Landingsyrs = subset(Landings, Yr > (Dat_start_mod1 - 1) & Yr <= (LastYR + 1))
    
  
    
   # Relatvie exploitation rate, extract, subset and merge
   Exploit = mod1$derived_quants[grep('F', mod1$derived_quants$Label), ]
   Exploit = Exploit[c(-1, -2), ]
   Exploityrs = Exploit[Exploit$Label >= paste('F_', Dat_start_mod1, sep = '') &  
                        Exploit$Label <= paste('F_', LastYR + 1, sep = ''), ]  
   Exploityrs$Yr = Exploityrs$Label1 = substr(Exploityrs$Label, 
                                               (nchar(Exploityrs$Label) + 1) - 4,
                                                nchar(Exploityrs$Label))
   Exploityrs$Yr = as.numeric(Exploityrs$Yr)
   Exploited = merge(Depl_years, Exploityrs, all.x=T, all.y=T, by.x='Yr', by.y='Yr')
   Exploited[is.na(Exploited)] <- 0
   Exploited$total = Exploited$Depl + Exploited$Value
    
  # SPR, extract and subset years
  SPR = mod1$sprseries[, c('Yr', 'SPR')]
  SPRyrs = subset(SPR, Yr > (Dat_start_mod1 - 1) & Yr <= (LastYR + 1))
  
  # fix %unfished values for first years
  for(irow in 1:2){
    if(Depleteyrs$total[irow] == 0){
      Depleteyrs$total[irow] <- 1.0
    }
  }
  
  # Bind all the columns together for the table
  Timeseries = as.data.frame(cbind(seq(Dat_start_mod1, LastYR + 1, 1), 
                                       Bio_allyrs$Bio_all, 
                                       SpawningByrs$Value,
                                       Depleteyrs$total,
                                       Recruityrs$Value, 
                                       Landingsyrs$Dead_Catch_B, 
                                       Exploited$total,
                                       SPRyrs$SPR))

 # Add colulmn names    
 colnames(Timeseries)=c('Yr', 
                        'Total biomass (mt)', 
                        paste0('Spawning biomass', SpawningB_units, ' (mt)'),
                        'Fraction unfished', 
                        'Age-0 recruits', 
                        'Total catch (mt)',
                        'Relative exploitation rate', 
                        'SPR')
 
 # Make year a factor so you don't have a decimal   
 Timeseries$Yr = as.factor(Timeseries$Yr)
    
 # Remove 2015 values for last three columns since year isn't complete
 Timeseries[nrow(Timeseries), c((ncol(Timeseries) - 2):ncol(Timeseries))] <- NA
```

\FloatBarrier
<!-- ---------------------------------------------------------------------- -->


\FloatBarrier

```{r, results='asis'}
    # xtable commands repeated from Exec_summary_figs_tables.R to change the label
    
    OFL.table = xtable(project,
        caption=c('Projections of landings, total mortality, OFL, and ACL values.'),
        label = 'tab:OFL_projection',
        digits = c(0,0,1,1,1,1,3)) 
    
    align(OFL.table) = c('l', 'l',
                           '>{\\centering}p{0.8in}',
                           '>{\\centering}p{1.2in}',
                           '>{\\centering}p{0.8in}',
                           '>{\\centering}p{0.8in}',
                           '>{\\centering}p{0.8in}')
    

    # Print OFL table 
      print(OFL.table, include.rownames = FALSE, caption.placement = 'top')
```

\FloatBarrier
\clearpage

```{r, results='asis'}   
# Decision tables is the same as the one in the Exec Summary created in
# R_exec_summary_figs_tables.R.  For some reason, it has to be re-created here.

# Read in decision table file
decision_mod1 = read.csv('./txt_files/DecisionTable_mod1.csv')
colnames(decision_mod1) = c('', 
                            'Year',  
                            'Catch',	
                            'Spawning Biomass',	
                            'Frac. Unfished', 
                            'Spawning Biomass',	
                            'Frac. Unfished',	
                            'Spawning Biomass',	
                            'Frac. Unfished')

decision_mod1.table = xtable(decision_mod1, 
                             caption = c(paste0('Summary of 12-year projections beginning in 2019',
                                                ' for alternate states of nature based the axis of uncertainty for the model.',
                                                ' Columns range over low, mid, and high states of nature, and rows range over different', 
                                                ' assumptions of catch levels.')), 
                             digits = c(0,0,0,1,0,3,0,3,0,3),
                             label='tab:Decision_table_mod1_text')

# Assign alignment and add the header columns
align(decision_mod1.table) = c('l','l|','c','c|','>{\\centering}p{.7in}','c|','>{\\centering}p{.7in}','c|','>{\\centering}p{.7in}','c') 

addtorow <- list()
addtorow$pos <- list()
addtorow$pos[[1]] <- -1
addtorow$pos[[2]] <- -1
addtorow$command <- c( ' \\multicolumn{3}{c}{}  &  \\multicolumn{2}{c}{} 
                               & \\multicolumn{2}{c}{\\textbf{States of nature}} 
                               & \\multicolumn{2}{c}{} \\\\\n', 
                       ' \\multicolumn{3}{c}{}  &  \\multicolumn{2}{c}{Low State} 
                               & \\multicolumn{2}{c}{Base State} 
                               &  \\multicolumn{2}{c}{High State} \\\\\n')

print(decision_mod1.table, add.to.row = addtorow, include.rownames = FALSE, 
      caption.placement = 'top', 
      hline.after = c(-1, 0, 12, 24, nrow(decision_mod1.table)), 
      scalebox = .85)
```

\FloatBarrier
```{r, results='asis'}
   # Print reference point tables

Ref_pts_mod1.table2 = xtable(Ref_pts_mod1, 
                            caption=c(paste('Summary of reference 
                                      points and management quantities for the 
                                      base case ', mod1_label, '.',sep = '')), 
                            label='tab:Ref_pts_mod1V2')  
# Add alignment      
align(Ref_pts_mod1.table2) = c('l',
                              '>{\\raggedright}p{4.1in}',
                              '>{\\raggedleft}p{.62in}',
                              '>{\\raggedleft}p{.62in}',
                              '>{\\raggedleft}p{.62in}')  


print(Ref_pts_mod1.table2, include.rownames = FALSE, caption.placement = 'top',
      sanitize.text.function = function(x){x})
   
```

\clearpage
\FloatBarrier
<!-- ====================================================================== --> 
<!-- *************************          *********************************** --> 
<!-- *************************END TABLES*********************************** --> 
<!-- *************************          *********************************** --> 
<!-- ====================================================================== --> 

